// This file is auto-generated by @hey-api/openapi-ts

import type { AdvanceControllerCreateAssetResponse, AdvanceControllerUpdateGeneralInformationsResponse, AssetControllerGetAssetResponse, AssetControllerUpdateCurrencyResponse, AssetControllerUpdateGeneralInformationsResponse, AssetControllerUpdateLocaleResponse, BillingControllerMigrateSapProductsResponse, EstimateControllerCreateAdvanceResponse, EstimateControllerCreateEstimateByContactOrOrganizationIdResponse, EstimateControllerRefuseResponse, EstimateControllerSignResponse, EstimateControllerUnrefuseResponse, EstimateControllerUnsignResponse, EstimateControllerUpdateAdvanceLinesResponse, EstimateControllerUpdateCurrencyResponse, EstimateControllerUpdateGeneralInformationsResponse, EstimateControllerUpdateLocaleResponse, EstimateControllerUpdateTimelineResponse, InvoiceControllerCreateAssetResponse, InvoiceControllerCreateInvoiceByContactOrOrganizationIdResponse, InvoiceControllerCreateInvoiceFrequencyResponse, InvoiceControllerDeleteInvoiceFrequencyResponse, InvoiceControllerGetInvoiceResponse, InvoiceControllerUpdateInvoiceCurrencyResponse, InvoiceControllerUpdateInvoiceFrequencyResponse, InvoiceControllerUpdateInvoiceGeneralInformationsResponse, InvoiceControllerUpdateInvoiceLocaleResponse, InvoiceControllerUpdateInvoicePaymentRequestResponse, InvoiceControllerUpdateTimelineResponse, OpportunityControllerCreateOpportunityResponse, OpportunityControllerRetrieveOpportunityResponse, OpportunityControllerUpdateOpportunityResponse } from './types.gen';

const readBillingCustomerDtoSchemaResponseTransformer = (data: any) => {
    if (data.parent) {
        data.parent = readBillingCustomerDtoSchemaResponseTransformer(data.parent);
    }
    return data;
};

const readAdvanceDtoSchemaResponseTransformer = (data: any) => {
    data.customer = readBillingCustomerDtoSchemaResponseTransformer(data.customer);
    if (data.parent) {
        data.parent = readEstimateDtoSchemaResponseTransformer(data.parent);
    }
    return data;
};

const readEstimateDtoSchemaResponseTransformer = (data: any) => {
    data.customer = readBillingCustomerDtoSchemaResponseTransformer(data.customer);
    data.advances = data.advances.map((item: any) => readAdvanceDtoSchemaResponseTransformer(item));
    return data;
};

export const estimateControllerCreateEstimateByContactOrOrganizationIdResponseTransformer = async (data: any): Promise<EstimateControllerCreateEstimateByContactOrOrganizationIdResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUpdateTimelineResponseTransformer = async (data: any): Promise<EstimateControllerUpdateTimelineResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerSignResponseTransformer = async (data: any): Promise<EstimateControllerSignResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUnsignResponseTransformer = async (data: any): Promise<EstimateControllerUnsignResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerRefuseResponseTransformer = async (data: any): Promise<EstimateControllerRefuseResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUnrefuseResponseTransformer = async (data: any): Promise<EstimateControllerUnrefuseResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerCreateAdvanceResponseTransformer = async (data: any): Promise<EstimateControllerCreateAdvanceResponse> => {
    data = readAdvanceDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUpdateGeneralInformationsResponseTransformer = async (data: any): Promise<EstimateControllerUpdateGeneralInformationsResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUpdateLocaleResponseTransformer = async (data: any): Promise<EstimateControllerUpdateLocaleResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUpdateCurrencyResponseTransformer = async (data: any): Promise<EstimateControllerUpdateCurrencyResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

export const estimateControllerUpdateAdvanceLinesResponseTransformer = async (data: any): Promise<EstimateControllerUpdateAdvanceLinesResponse> => {
    data = readEstimateDtoSchemaResponseTransformer(data);
    return data;
};

const readInvoiceDtoSchemaResponseTransformer = (data: any) => {
    data.customer = readBillingCustomerDtoSchemaResponseTransformer(data.customer);
    if (data.parent) {
        data.parent = readEstimateDtoSchemaResponseTransformer(data.parent);
    }
    return data;
};

export const invoiceControllerGetInvoiceResponseTransformer = async (data: any): Promise<InvoiceControllerGetInvoiceResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerCreateInvoiceByContactOrOrganizationIdResponseTransformer = async (data: any): Promise<InvoiceControllerCreateInvoiceByContactOrOrganizationIdResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateTimelineResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateTimelineResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateInvoicePaymentRequestResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateInvoicePaymentRequestResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateInvoiceGeneralInformationsResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateInvoiceGeneralInformationsResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateInvoiceLocaleResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateInvoiceLocaleResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateInvoiceCurrencyResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateInvoiceCurrencyResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerDeleteInvoiceFrequencyResponseTransformer = async (data: any): Promise<InvoiceControllerDeleteInvoiceFrequencyResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerCreateInvoiceFrequencyResponseTransformer = async (data: any): Promise<InvoiceControllerCreateInvoiceFrequencyResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const invoiceControllerUpdateInvoiceFrequencyResponseTransformer = async (data: any): Promise<InvoiceControllerUpdateInvoiceFrequencyResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

const readAssetDtoSchemaResponseTransformer = (data: any) => {
    data.customer = readBillingCustomerDtoSchemaResponseTransformer(data.customer);
    return data;
};

export const invoiceControllerCreateAssetResponseTransformer = async (data: any): Promise<InvoiceControllerCreateAssetResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

export const billingControllerMigrateSapProductsResponseTransformer = async (data: any): Promise<BillingControllerMigrateSapProductsResponse> => {
    data = readInvoiceDtoSchemaResponseTransformer(data);
    return data;
};

export const advanceControllerUpdateGeneralInformationsResponseTransformer = async (data: any): Promise<AdvanceControllerUpdateGeneralInformationsResponse> => {
    data = readAdvanceDtoSchemaResponseTransformer(data);
    return data;
};

export const advanceControllerCreateAssetResponseTransformer = async (data: any): Promise<AdvanceControllerCreateAssetResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

export const assetControllerGetAssetResponseTransformer = async (data: any): Promise<AssetControllerGetAssetResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

export const assetControllerUpdateGeneralInformationsResponseTransformer = async (data: any): Promise<AssetControllerUpdateGeneralInformationsResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

export const assetControllerUpdateLocaleResponseTransformer = async (data: any): Promise<AssetControllerUpdateLocaleResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

export const assetControllerUpdateCurrencyResponseTransformer = async (data: any): Promise<AssetControllerUpdateCurrencyResponse> => {
    data = readAssetDtoSchemaResponseTransformer(data);
    return data;
};

const readCustomerDtoSchemaResponseTransformer = (data: any) => {
    if (data.parent) {
        data.parent = readCustomerDtoSchemaResponseTransformer(data.parent);
    }
    return data;
};

const readOpportunityDtoSchemaResponseTransformer = (data: any) => {
    data.customer = readCustomerDtoSchemaResponseTransformer(data.customer);
    return data;
};

export const opportunityControllerRetrieveOpportunityResponseTransformer = async (data: any): Promise<OpportunityControllerRetrieveOpportunityResponse> => {
    data = readOpportunityDtoSchemaResponseTransformer(data);
    return data;
};

export const opportunityControllerUpdateOpportunityResponseTransformer = async (data: any): Promise<OpportunityControllerUpdateOpportunityResponse> => {
    data = readOpportunityDtoSchemaResponseTransformer(data);
    return data;
};

export const opportunityControllerCreateOpportunityResponseTransformer = async (data: any): Promise<OpportunityControllerCreateOpportunityResponse> => {
    data = readOpportunityDtoSchemaResponseTransformer(data);
    return data;
};
