// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * The mode of the advance (amount or percentage)
 */
export const zAdvanceMode = z.enum(['AMOUNT', 'PERCENTAGE']).register(z.globalRegistry, {
    description: 'The mode of the advance (amount or percentage)'
});

export const zAdvanceItemDto = z.object({
    value: z.number().register(z.globalRegistry, {
        description: 'The value of the advance (amount or percentage)'
    }),
    mode: zAdvanceMode,
    paymentCondition: z.optional(z.enum([
        'SIGNATURE',
        'ORDER',
        'OTHER'
    ]).register(z.globalRegistry, {
        description: 'Payment condition for the advance'
    })),
    customPaymentCondition: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zBankInformationDto = z.object({
    bic: z.string(),
    iban: z.string(),
    holder: z.string()
});

export const zBankInformationsDto = z.object({
    iban: z.string().register(z.globalRegistry, {
        description: 'International Bank Account Number'
    }),
    bic: z.string().register(z.globalRegistry, {
        description: 'Bank Identifier Code'
    }),
    holder: z.string().register(z.globalRegistry, {
        description: 'Name of the account holder'
    })
});

export const zBillingCompatibilityVersion = z.enum(['V1', 'V2']);

export const zBillingEmailType = z.enum([
    'invoice_simple',
    'invoice_reminder',
    'invoice_recurring',
    'estimate_simple'
]);

export const zBillingLocale = z.enum([
    'fr',
    'en',
    'de',
    'it',
    'nl',
    'pt',
    'es'
]);

export const zBillingState = z.enum([
    'draft',
    'finalized',
    'signed',
    'refused',
    'paid'
]);

export const zBillingType = z.enum([
    'estimate',
    'invoice',
    'asset',
    'advance',
    'purchase_order'
]);

/**
 * Current client state
 */
export const zClientState = z.enum([
    'synced',
    'pending',
    'end_user_action_required',
    'error'
]).register(z.globalRegistry, {
    description: 'Current client state'
});

export const zContactOrderBy = z.enum(['name', 'createdAt']);

export const zConvertedAmountsLineDto = z.object({
    priceWithoutTaxBeforeDiscount: z.number(),
    discountAmount: z.optional(z.number()),
    priceWithoutTaxAfterDiscount: z.number(),
    vatAmount: z.number(),
    priceTotalTax: z.number()
});

/**
 * Country code of the address
 */
export const zCountryCode = z.enum([
    'AF',
    'AX',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AN',
    'AR',
    'AM',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BQ',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'KH',
    'CM',
    'CA',
    'CV',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CG',
    'CD',
    'CK',
    'CR',
    'CI',
    'HR',
    'CU',
    'CW',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KR',
    'XK',
    'KP',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MK',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SX',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'SS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SZ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UM',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW'
]).register(z.globalRegistry, {
    description: 'Country code of the address'
});

export const zAddressDto = z.object({
    line1: z.string().register(z.globalRegistry, {
        description: 'First line of the address'
    }),
    line2: z.optional(z.string().register(z.globalRegistry, {
        description: 'Second line of the address'
    })),
    city: z.string().register(z.globalRegistry, {
        description: 'City of the address'
    }),
    zipCode: z.string().register(z.globalRegistry, {
        description: 'Zip code of the address'
    }),
    country: zCountryCode
});

export const zClientAddressDto = z.object({
    address: z.union([
        z.string(),
        z.null()
    ]),
    complement: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    city: z.union([
        z.string(),
        z.null()
    ]),
    zipCode: z.union([
        z.string(),
        z.null()
    ]),
    state: z.optional(z.string().register(z.globalRegistry, {
        description: 'The state or province of the address'
    })),
    country: zCountryCode
});

export const zCreateOpportunityDto = z.object({
    name: z.string().register(z.globalRegistry, {
        description: 'The name of the opportunity'
    }),
    description: z.optional(z.string().register(z.globalRegistry, {
        description: 'The description of the opportunity'
    })),
    dueDate: z.optional(z.string().register(z.globalRegistry, {
        description: 'The due date as ISO date string YYYY-MM-DD'
    })),
    amount: z.number().register(z.globalRegistry, {
        description: 'The amount in cents'
    }),
    customerId: z.string().register(z.globalRegistry, {
        description: 'The legacy customer ID'
    }),
    categoryId: z.string().register(z.globalRegistry, {
        description: 'The category ID'
    }),
    afterRank: z.optional(z.string().register(z.globalRegistry, {
        description: 'The rank to insert after'
    }))
});

export const zCreateOrganizationContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.optional(z.string()),
    jobTitle: z.optional(z.string()),
    emails: z.optional(z.array(z.string())),
    notes: z.optional(z.string())
});

export const zCurrencyCode = z.enum([
    'EUR',
    'GBP',
    'CHF',
    'USD',
    'AUD',
    'CAD',
    'JPY',
    'CNH',
    'CZK',
    'DKK',
    'BGN',
    'PLN',
    'HUF',
    'RON',
    'SEK',
    'NOK',
    'TRY',
    'BRL',
    'HKD',
    'ILS',
    'INR',
    'KRW',
    'MXN'
]);

export const zClientPreferencesDto = z.object({
    language: z.optional(zBillingLocale),
    currency: z.optional(zCurrencyCode),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'The client\'s preferred payment methods'
    }))
});

export const zCreateContactDto = z.object({
    firstname: z.string().register(z.globalRegistry, {
        description: 'The first name of the contact'
    }),
    lastname: z.string().register(z.globalRegistry, {
        description: 'The last name of the contact'
    }),
    phone: z.optional(z.string().register(z.globalRegistry, {
        description: 'The phone number of the contact'
    })),
    jobTitle: z.optional(z.string().register(z.globalRegistry, {
        description: 'The job title of the contact'
    })),
    emails: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'The email addresses of the contact'
    })),
    notes: z.optional(z.string().register(z.globalRegistry, {
        description: 'Additional notes about the contact'
    })),
    billingAddress: z.optional(zClientAddressDto),
    deliveryAddress: z.optional(zClientAddressDto),
    bankInformations: z.optional(zBankInformationsDto),
    preferences: z.optional(zClientPreferencesDto)
});

export const zCreateOrganizationDto = z.object({
    name: z.string().register(z.globalRegistry, {
        description: 'The official name of the organization'
    }),
    commercialName: z.optional(z.string().register(z.globalRegistry, {
        description: 'The commercial or trading name of the organization'
    })),
    emails: z.optional(z.array(z.string())),
    siret: z.optional(z.string().register(z.globalRegistry, {
        description: 'The SIRET number (required for French organizations)'
    })),
    vatNumber: z.optional(z.string().register(z.globalRegistry, {
        description: 'The VAT number of the organization'
    })),
    billingAddress: z.optional(zClientAddressDto),
    deliveryAddress: z.optional(zClientAddressDto),
    notes: z.optional(z.string().register(z.globalRegistry, {
        description: 'Additional notes about the organization'
    })),
    bankInformations: z.optional(zBankInformationsDto),
    preferences: z.optional(zClientPreferencesDto)
});

export const zCurrencyOrigin = z.enum(['ECB', 'USER']);

export const zCustomerPortalBillingDto = z.object({
    id: z.string(),
    number: z.string(),
    date: z.number(),
    billingState: zBillingState,
    billingType: zBillingType,
    amount: z.number(),
    signatureId: z.optional(z.string()),
    signature: z.optional(z.record(z.string(), z.unknown())),
    dueDate: z.optional(z.number()),
    validityDate: z.optional(z.number())
});

export const zCustomerPortalCompanyDto = z.object({
    commercialName: z.string(),
    name: z.string()
});

export const zCustomerPortalCustomerDto = z.object({
    name: z.string(),
    firstname: z.optional(z.string()),
    lastname: z.optional(z.string())
});

/**
 * Type de remise sur acompte
 */
export const zDiscountAdvancePayment = z.enum(['none', 'other']).register(z.globalRegistry, {
    description: 'Type de remise sur acompte'
});

export const zBillingDiscountAdvancePaymentDto = z.object({
    value: zDiscountAdvancePayment,
    otherValue: z.optional(z.string().register(z.globalRegistry, {
        description: 'Description custom si `value` vaut `other`'
    }))
});

/**
 * Mode de la réduction en pourcentage ou en euros
 */
export const zDiscountMode = z.enum(['PERCENTAGE', 'AMOUNT']).register(z.globalRegistry, {
    description: 'Mode de la réduction en pourcentage ou en euros'
});

export const zDiscountDto = z.object({
    mode: zDiscountMode,
    amount: z.number().register(z.globalRegistry, {
        description: 'The amount for the discount (1000 for 10% or 10€)'
    })
});

export const zDiscountLineDto = z.object({
    amount: z.number().register(z.globalRegistry, {
        description: 'Montant de la remise, 1000 pour 10% ou 10€'
    }),
    mode: zDiscountMode
});

export const zDisplayBillingSettingsDto = z.object({
    displayFullName: z.boolean(),
    displayEmail: z.boolean(),
    displayPhoneNumber: z.boolean(),
    displaySAPAgreement: z.boolean(),
    displayLegalStatus: z.boolean(),
    displayRequiredMentionsProduct: z.boolean(),
    displayMemberOfAnApprovedAssociation: z.boolean(),
    displayAbbyLogo: z.boolean(),
    displayTitle: z.boolean(),
    displayGoodForApproval: z.optional(z.boolean()),
    displayEstimateNumber: z.optional(z.boolean())
});

export const zDisplaySettingsDto = z.object({
    displayFullName: z.boolean(),
    displayEmail: z.boolean(),
    displayPhoneNumber: z.boolean(),
    displaySAPAgreement: z.boolean(),
    displayLegalStatus: z.boolean(),
    displayRequiredMentionsProduct: z.boolean(),
    displayGoodForApproval: z.optional(z.boolean()),
    displayMemberOfAnApprovedAssociation: z.boolean(),
    displayAbbyLogo: z.boolean(),
    displayTitle: z.boolean()
});

export const zElectronicSignatureRequirementDto = z.object({
    name: z.string(),
    message: z.string()
});

export const zElectronicSignatureStatus = z.enum([
    'requested',
    'activated',
    'on_going',
    'refused',
    'signed',
    'cancelled'
]);

export const zEstimateElectronicSignatureDto = z.object({
    id: z.string(),
    canceledAt: z.union([
        z.number(),
        z.null()
    ]),
    procedureId: z.union([
        z.string(),
        z.null()
    ]),
    magicLink: z.union([
        z.string(),
        z.null()
    ]),
    signedAt: z.union([
        z.number(),
        z.null()
    ]),
    refusedAt: z.union([
        z.number(),
        z.null()
    ]),
    status: zElectronicSignatureStatus
});

export const zEstimateType = z.enum(['estimate', 'purchase_order']);

export const zCreateEstimateByCustomerIdDto = z.object({
    estimateType: z.optional(zEstimateType)
});

export const zFinalizeRequirementDto = z.object({
    name: z.string(),
    message: z.string()
});

export const zFrequencyInterval = z.enum([
    'day',
    'week',
    'month',
    'year'
]);

export const zCreateInvoiceFrequencyDto = z.object({
    from: z.string(),
    to: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zFrequencyDto = z.object({
    id: z.string(),
    from: z.string(),
    to: z.string(),
    nextBillingAt: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zLatePenalty = z.enum([
    'three_time_legal_rate',
    'bce_director_rate_plus_ten_points',
    'other'
]);

export const zBillingLatePenaltyDto = z.object({
    value: zLatePenalty,
    otherValue: z.optional(z.string().register(z.globalRegistry, {
        description: 'Description custom si `value` vaut `other`'
    }))
});

export const zLatePenaltyDto = z.object({
    value: zLatePenalty,
    otherValue: z.optional(z.string().register(z.globalRegistry, {
        description: 'Description custom si `value` vaut `other`'
    }))
});

export const zLegalStatus = z.enum([
    'micro_enterprise',
    'sas',
    'sarl',
    'sasu',
    'ei',
    'eurl',
    'eirl',
    'sa',
    'snc',
    'other',
    'sasu_sas',
    'eurl_sarl',
    'sci',
    'association'
]);

export const zCompanyDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Identifiant unique de l\'entreprise'
    }),
    commercialName: z.string().register(z.globalRegistry, {
        description: 'Nom commercial de l\'entreprise'
    }),
    siret: z.string().register(z.globalRegistry, {
        description: 'Numéro SIRET de l\'entreprise'
    }),
    legalStatut: zLegalStatus,
    address: z.string().register(z.globalRegistry, {
        description: 'Adresse de l\'entreprise'
    }),
    city: z.string().register(z.globalRegistry, {
        description: 'Ville de l\'entreprise'
    }),
    isInTestMode: z.boolean().register(z.globalRegistry, {
        description: 'Indique si l\'entreprise est en mode test'
    })
});

export const zLumpSumCompensation = z.enum(['forty_euros', 'other']);

export const zBillingLumpSumCompensationDto = z.object({
    value: zLumpSumCompensation,
    otherValue: z.optional(z.string().register(z.globalRegistry, {
        description: 'Description custom si `value` vaut `other`'
    }))
});

export const zLumpSumCompensationDto = z.object({
    value: zLumpSumCompensation,
    otherValue: z.optional(z.string().register(z.globalRegistry, {
        description: 'Description custom si `value` vaut `other`'
    }))
});

export const zOpportunityDto = z.object({
    id: z.string(),
    name: z.string()
});

export const zOrderDirection = z.enum(['ASC', 'DESC']);

export const zOrganizationDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Organization ID'
    }),
    name: z.string().register(z.globalRegistry, {
        description: 'Organization name'
    })
});

export const zOrganizationOrderBy = z.enum(['name', 'createdAt']);

/**
 * The reason of the payment account
 */
export const zPaymentAccountIssueReason = z.enum([
    'MISSING_INFO',
    'UNDER_REVIEW',
    'FRAUD_SUSPECTED',
    'TERMS_VIOLATION',
    'UNKNOWN'
]).register(z.globalRegistry, {
    description: 'The reason of the payment account'
});

/**
 * The status of the payment account
 */
export const zPaymentAccountStatus = z.enum(['enabled', 'disabled']).register(z.globalRegistry, {
    description: 'The status of the payment account'
});

/**
 * Payment condition for the advance
 */
export const zPaymentCondition = z.enum([
    'SIGNATURE',
    'ORDER',
    'OTHER'
]).register(z.globalRegistry, {
    description: 'Payment condition for the advance'
});

export const zPaymentDelay = z.enum([
    'at_reception',
    'end_of_month',
    'seven_days',
    'ten_days',
    'fifteen_days',
    'thirty_days',
    'thirty_days_end_of_month',
    'forty_five_days',
    'forty_five_days_end_of_month',
    'sixty_days',
    'sixty_days_end_of_month',
    'ninety_days',
    'ninety_days_end_of_month',
    'one_hundred_and_twenty_days',
    'other'
]);

export const zPaymentMethod = z.enum([
    'transfer',
    'direct_debit',
    'credit_card',
    'cheque',
    'universal_employment_service_cheque',
    'cash',
    'paypal',
    'stripe',
    'other'
]);

/**
 * The provider of the payment account
 */
export const zPaymentProvider = z.enum(['stripe_connect']).register(z.globalRegistry, {
    description: 'The provider of the payment account'
});

export const zPaymentRequestPayloadDto = z.object({
    advanceAlreadyPaid: z.number().register(z.globalRegistry, {
        description: 'Amount in cents of the advance already paid. This amount must not exceed 50% of the total including or excluding tax of the invoice.'
    }),
    dateDebutEmploi: z.number().register(z.globalRegistry, {
        description: 'Date of the beginning of the employment period.'
    }),
    dateFinEmploi: z.number().register(z.globalRegistry, {
        description: 'Date of the end of the employment period.'
    })
});

export const zPaymentRequestStatusUrssafTp = z.union([
    z.literal(0),
    z.literal('10'),
    z.literal('20'),
    z.literal('30'),
    z.literal('40'),
    z.literal('50'),
    z.literal('70'),
    z.literal('60'),
    z.literal('110'),
    z.literal('111'),
    z.literal('120'),
    z.literal('112'),
    z.literal('ERR_PARTICULIER_INCONNU'),
    z.literal('ERR_CMPT_BLOQUE'),
    z.literal('ERR_FACTURE_DOUBLON'),
    z.literal('ERR_NBRE_PREST_MAX'),
    z.literal('ERR_DATE_FUTUR'),
    z.literal('ERR_DATE_PAIEMENT_AVANT_EXP'),
    z.literal('ERR_PERIODE_EMPLOI_MOIS_NON_UNIQUE'),
    z.literal('ERR_DATE_FIN_AVANT_DATE_DEB'),
    z.literal('ERR_MONTANT_ACOMPTE'),
    z.literal('ERR_TOTAL_PRESTATIONS'),
    z.literal('ERR_CODE_NATURE'),
    z.literal('ERR_CODE_ACTIVITE'),
    z.literal('ERR_CODE_ACTIVITE_NATURE'),
    z.literal('ERR_MNT_PREST_HT_TVA'),
    z.literal('ERR_MNT_PREST_TTC'),
    z.literal('ERR_VALEUR_NEGATIVE'),
    z.literal('ERR_PRESTATAIRE_EMETTEUR_INCONNU'),
    z.literal('ERR_LIEN_PARTICULIER_PRESTATAIRE'),
    z.literal('ERR_PRESTATAIRE_FACTURATION_INCONNU'),
    z.literal('ERR_CRITERE_RECHERCHE_VIDE'),
    z.literal('ERR_DGFIP_R2P_INCONNU'),
    z.literal('ERR_DATE_NAISSANCE_FUTUR'),
    z.literal('ERR_LIEU_NAISSANCE_DEPT'),
    z.literal('ERR_LIEU_NAISSANCE_COMN'),
    z.literal('ERR_LIEU_NAISSANCE_PAYS'),
    z.literal('ERR_DGFIP_IMPOTPART_INCONNU'),
    z.literal('ERR_CONTACT'),
    z.literal('ERR_CONTACT_ADRESSE_TYPE_VOIE'),
    z.literal('ERR_CONTACT_ADRESSE_LETTRE_VOIE'),
    z.literal('ERR_CONTACT_ADRESSE_TYPEVOIE'),
    z.literal('ERR_CONTACT_ADRESSE_LIBELLEVOIE'),
    z.literal('ERR_CONTACT_ADRESSE_INFORMATION_SUPPLEMENTAIRE'),
    z.literal('ERR_CONTACT_ADRESSE_COMMUNE'),
    z.literal('ERR_COORDONNEES_BANCAIRES'),
    z.literal('ERR_FORMAT_VALEUR'),
    z.literal('ERR_NBRE_MAX_RESULTAT'),
    z.literal('ERR_RECHERCHE_VIDE'),
    z.literal('ERR_ECV_PARTICULIERS_EXISTENT'),
    z.literal('ERREUR_REFERENCE_PARTICULIER_EXISTANTE_TYPE'),
    z.literal('ERR_LIEU_NAISSANCE_OBLIGATOIRE'),
    z.literal('ERREUR_LIEU_NAISSANCE_INVALIDE'),
    z.literal('ERR_RECHERCHE_PARTICULIER'),
    z.literal('ERR_FORMAT_NUMINTERVENANT'),
    z.literal('ERR_NUMINTERVENANT_MANQUANT'),
    z.literal('ERR_NUMINTERVENANT_BLOQUE'),
    z.literal('ERR_MANDAT_ECHU'),
    z.literal('ERREUR_VALIDATION'),
    z.literal('ERREUR_TECHNIQUE'),
    z.literal('ERREUR_INCONNUE')
]);

export const zPaymentRequestDto = z.object({
    idDemandePaiement: z.optional(z.string()),
    dateDebutEmploi: z.number(),
    dateFinEmploi: z.number(),
    dateVirement: z.optional(z.number()),
    advanceAlreadyPayed: z.optional(z.number()),
    mntVirement: z.optional(z.number()),
    statut: z.optional(zPaymentRequestStatusUrssafTp)
});

export const zPersonalServiceActivity = z.enum([
    'GARDE_ENFANT_HANDICAPE',
    'ACCOMPAGNEMENT_ENFANT_HANDICAPE',
    'AIDE_HUMAINE',
    'CONDUITE_VEHICULE_PERSONNEL',
    'AIDE_AU_DEPLACEMENT',
    'ENTRETIEN_DE_LA_MAISON',
    'JARDINAGE',
    'BRICOLAGE',
    'GARDE_ENFANT_PLUS_DE_6_ANS',
    'SOUTIEN_SCOLAIRE_COURS_A_DOMICILE',
    'SOIN_ESTHETIQUE_A_DOMICILE',
    'PREPARATION_REPAS_A_DOMICILE',
    'LIVRAISON_REPAS_A_DOMICILE',
    'COLLECTE_ET_LIVRAISON_DE_LINGE_REPASSE',
    'LIVRAISON_COURSES_A_DOMICILE',
    'ASSISTANCE_INFORMATIQUE',
    'SOINS_ET_PROMENADES_ANIMAUX_DE_COMPAGNIE_POUR_PERSONNES_DEPENDANTES',
    'MAINTENANCE_ENTRETIEN_ET_VIGILANCE_DE_LA_RESIDENCE_PRINCIPALE',
    'ASSISTANCE_ADMINISTRATIVE',
    'ACCOMPAGNEMENT_ENFANT_PLUS_DE_6_ANS',
    'TELEASSISTANCE',
    'INTERPRETE_LANGUE_DES_SIGNES',
    'CONDUITE_VEHICULE_PERSONNEL_EN_CAS_INVALIDITE_TEMPORAIRE',
    'ACCOMPAGNEMENT_DEPLACEMENTS_EN_DEHORS_DU_DOMICILE',
    'ASSISTANCE_PERSONNES_TEMPORAIREMENT_DEPENDANTES_A_DOMICILE',
    'COORDINATION_ET_GESTION',
    'DIVERS_NON_ELIGIBLE'
]);

export const zProductType = z.enum([
    'sale_of_goods',
    'service_delivery',
    'commercial_or_craft_services',
    'sale_of_manufactured_goods',
    'disbursement'
]);

export const zProductUnit = z.enum([
    'unit',
    'gram',
    'hour',
    'day',
    'week',
    'fixed_rate',
    'year',
    'character',
    'line',
    'license',
    'article',
    'month',
    'kilogram',
    'kilometer',
    'liter',
    'batch',
    'meter',
    'square_meter',
    'cubic_meter',
    'linear_meter',
    'person',
    'ton',
    'word',
    'page',
    'leaflet',
    'paragraph',
    'minute',
    'overnight_stay'
]);

export const zMigrateSapProductLineDto = z.object({
    lineId: z.string().register(z.globalRegistry, {
        description: 'ID of the billing line to update'
    }),
    ignore: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'If true, the line will not be included as a personal service product'
    })),
    quantityUnit: z.optional(zProductUnit),
    personalServiceActivity: z.optional(zPersonalServiceActivity)
});

export const zMigrateSapProductsDto = z.object({
    lines: z.array(zMigrateSapProductLineDto).register(z.globalRegistry, {
        description: 'Lines to migrate for SAP compliance'
    })
});

export const zPushNotificationPreferencesDto = z.object({
    urssafReminder: z.boolean().register(z.globalRegistry, {
        description: 'Urssaf reminders'
    })
});

export const zNotificationPreferencesDto = z.object({
    push: zPushNotificationPreferencesDto
});

export const zReadAdvanceItemLineDto = z.object({
    value: z.number().register(z.globalRegistry, {
        description: 'The value of the advance (amount or percentage)'
    }),
    mode: zAdvanceMode,
    paymentCondition: z.optional(zPaymentCondition),
    customPaymentCondition: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zReadAdvanceItemLineTotalsDto = z.object({
    totalAmountWithoutTax: z.number().register(z.globalRegistry, {
        description: 'Total amount of all advances'
    }),
    totalAmountWithTax: z.number().register(z.globalRegistry, {
        description: 'Total amount of all advances after discount'
    }),
    remainingTotalAmountWithoutTax: z.number().register(z.globalRegistry, {
        description: 'Remaining total amount without tax'
    }),
    remainingTotalAmountWithTax: z.number().register(z.globalRegistry, {
        description: 'Remaining total amount with tax'
    })
});

export const zReadBankInformationDto = z.object({
    bic: z.string(),
    iban: z.string(),
    holder: z.string()
});

export const zReadBillingCustomerDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Unique identifier of the customer'
    }),
    legacyId: z.string().register(z.globalRegistry, {
        description: 'Legacy identifier of the customer'
    }),
    currency: z.optional(zCurrencyCode),
    firstname: z.optional(z.string().register(z.globalRegistry, {
        description: 'First name of the customer'
    })),
    lastname: z.optional(z.string().register(z.globalRegistry, {
        description: 'Last name of the customer'
    })),
    phoneNumber: z.optional(z.string().register(z.globalRegistry, {
        description: 'Phone number of the customer'
    })),
    emails: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Email addresses of the customer'
    })),
    billingAddress: zAddressDto,
    deliveryAddress: z.optional(zAddressDto),
    deliveryAddressIsSame: z.boolean().register(z.globalRegistry, {
        description: 'Tell if delivery and billing address are deep equal or not'
    }),
    language: z.optional(z.string().register(z.globalRegistry, {
        description: 'Preferred language of the customer'
    })),
    name: z.optional(z.string().register(z.globalRegistry, {
        description: 'Full name of the customer'
    })),
    commercialName: z.optional(z.string().register(z.globalRegistry, {
        description: 'Commercial name of the customer'
    })),
    siren: z.optional(z.string().register(z.globalRegistry, {
        description: 'SIREN number of the customer'
    })),
    siret: z.optional(z.string().register(z.globalRegistry, {
        description: 'SIRET number of the customer'
    })),
    nafCode: z.optional(z.string().register(z.globalRegistry, {
        description: 'NAF code of the customer'
    })),
    vatNumber: z.optional(z.string().register(z.globalRegistry, {
        description: 'VAT number of the customer'
    })),
    token: z.string().register(z.globalRegistry, {
        description: 'Token associated with the customer'
    }),
    get parent() {
        return z.optional(z.lazy((): any => zReadBillingCustomerDto));
    },
    contactId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Contact identifier associated with the customer'
    })),
    organizationId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Organization identifier associated with the customer'
    })),
    isDefault: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Indicates if this is the default customer'
    })),
    test: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if this is a test customer'
    })
});

export const zReadBillingEmailDto = z.object({
    subject: z.string().register(z.globalRegistry, {
        description: 'The subject of the email with rendered variables'
    }),
    content: z.string().register(z.globalRegistry, {
        description: 'The content of the email with rendered variables'
    })
});

export const zReadBillingEmitterDto = z.object({
    name: z.optional(z.string()),
    fullName: z.optional(z.string()),
    email: z.optional(z.string()),
    phone: z.optional(z.string()),
    commercialName: z.optional(z.string()),
    siret: z.optional(z.string()),
    vatNumber: z.optional(z.string()),
    rcsNumber: z.optional(z.string()),
    legalStatus: z.optional(zLegalStatus),
    sapAgreementNumber: z.optional(z.string()),
    hasVat: z.optional(z.boolean())
});

export const zReadCategoryDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'The category ID'
    }),
    companyId: z.string().register(z.globalRegistry, {
        description: 'The company ID'
    }),
    name: z.string().register(z.globalRegistry, {
        description: 'The name of the category'
    }),
    rank: z.string().register(z.globalRegistry, {
        description: 'The rank for ordering'
    }),
    showDueDate: z.boolean().register(z.globalRegistry, {
        description: 'Show due date on opportunities'
    }),
    showAmount: z.boolean().register(z.globalRegistry, {
        description: 'Show amount on opportunities'
    }),
    showCustomer: z.boolean().register(z.globalRegistry, {
        description: 'Show customer on opportunities'
    }),
    color: z.string().register(z.globalRegistry, {
        description: 'The color of the category (hex)'
    }),
    isLost: z.boolean().register(z.globalRegistry, {
        description: 'Whether this is a lost category'
    }),
    isDone: z.boolean().register(z.globalRegistry, {
        description: 'Whether this is a done category'
    }),
    count: z.number().register(z.globalRegistry, {
        description: 'Number of opportunities in this category'
    })
});

export const zReadContactDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Contact ID'
    }),
    emails: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Contact email addresses'
    })),
    organization: z.optional(zOrganizationDto),
    defaultContact: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Whether this is the default contact'
    })),
    createdAt: z.number().register(z.globalRegistry, {
        description: 'Contact creation timestamp'
    }),
    archivedAt: z.optional(z.number().register(z.globalRegistry, {
        description: 'Contact archival timestamp'
    })),
    hasBillings: z.boolean().register(z.globalRegistry, {
        description: 'Whether the contact has billings'
    }),
    test: z.boolean().register(z.globalRegistry, {
        description: 'Whether this is a test contact'
    }),
    phone: z.optional(z.string().register(z.globalRegistry, {
        description: 'Contact phone number'
    })),
    firstname: z.string().register(z.globalRegistry, {
        description: 'Contact first name'
    }),
    lastname: z.string().register(z.globalRegistry, {
        description: 'Contact last name'
    }),
    billingAddress: z.optional(zClientAddressDto),
    deliveryAddress: z.optional(zClientAddressDto),
    jobTitle: z.optional(z.string().register(z.globalRegistry, {
        description: 'Contact job title'
    })),
    bankInformations: z.optional(zBankInformationsDto),
    hasTiersPrestation: z.boolean().register(z.globalRegistry, {
        description: 'Whether the contact has third-party services'
    }),
    notes: z.optional(z.string().register(z.globalRegistry, {
        description: 'Additional notes about the contact'
    })),
    language: z.optional(zBillingLocale),
    currency: z.optional(zCurrencyCode),
    paymentMethods: z.optional(zPaymentMethod)
});

export const zReadCurrencyDto = z.object({
    currencyCode: zCurrencyCode,
    currencyDate: z.number(),
    currencyRate: z.number(),
    origin: zCurrencyOrigin
});

export const zReadCustomerAddressDto = z.object({
    line1: z.string().register(z.globalRegistry, {
        description: 'First line of address'
    }),
    line2: z.optional(z.string().register(z.globalRegistry, {
        description: 'Second line of address'
    })),
    city: z.string().register(z.globalRegistry, {
        description: 'City name'
    }),
    zipCode: z.string().register(z.globalRegistry, {
        description: 'Postal/ZIP code'
    }),
    country: zCountryCode
});

export const zReadEstimateAdvanceLinesDto = z.object({
    advances: z.array(zReadAdvanceItemLineDto).register(z.globalRegistry, {
        description: 'Array of advance items'
    }),
    totals: zReadAdvanceItemLineTotalsDto,
    convertedTotals: zReadAdvanceItemLineTotalsDto
});

export const zReadFileDto = z.object({
    id: z.string(),
    name: z.string(),
    extension: z.string(),
    mimeType: z.string(),
    url: z.string(),
    relativeUrl: z.string(),
    isCertified: z.optional(z.boolean()),
    isCertifiable: z.optional(z.boolean())
});

export const zReadOrganizationDto = z.object({
    language: z.optional(zBillingLocale),
    currency: z.optional(zCurrencyCode),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'The client\'s preferred payment methods'
    })),
    id: z.string(),
    name: z.string(),
    commercialName: z.string(),
    emails: z.array(z.string()),
    siret: z.string(),
    vatNumber: z.string(),
    countContacts: z.number(),
    billingAddress: zClientAddressDto,
    deliveryAddress: zClientAddressDto,
    bankInformations: zBankInformationsDto,
    notes: z.string(),
    createdAt: z.number().register(z.globalRegistry, {
        description: 'Contact creation timestamp'
    }),
    archivedAt: z.number().register(z.globalRegistry, {
        description: 'Contact archival timestamp'
    }),
    hasBillings: z.boolean(),
    test: z.boolean()
});

export const zReadOrganizationsDto = z.object({
    countWithoutFilters: z.number(),
    totalDocs: z.number(),
    limit: z.number(),
    totalPages: z.number(),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    nextPage: z.number(),
    page: z.number(),
    prevPage: z.number(),
    docs: z.array(zReadOrganizationDto)
});

export const zReadPaymentAccountDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'The ID of the payment account'
    }),
    externalId: z.string().register(z.globalRegistry, {
        description: 'The external ID of the payment account'
    }),
    provider: zPaymentProvider,
    status: zPaymentAccountStatus,
    reason: z.union([
        zPaymentAccountIssueReason,
        z.null()
    ])
});

export const zReadTiersPrestationDto = z.object({
    idClient: z.string().register(z.globalRegistry, {
        description: 'Client identifier'
    }),
    registeredAt: z.number().register(z.globalRegistry, {
        description: 'Registration timestamp'
    }),
    status: zClientState
});

export const zReadCustomerDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Unique identifier'
    }),
    legacyId: z.string().register(z.globalRegistry, {
        description: 'Legacy system identifier'
    }),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'List of payment method identifiers'
    })),
    currency: z.optional(zCurrencyCode),
    firstname: z.optional(z.string().register(z.globalRegistry, {
        description: 'Customer first name'
    })),
    lastname: z.optional(z.string().register(z.globalRegistry, {
        description: 'Customer last name'
    })),
    phoneNumber: z.optional(z.string().register(z.globalRegistry, {
        description: 'Contact phone number'
    })),
    emails: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'List of email addresses'
    })),
    billingAddress: zReadCustomerAddressDto,
    deliveryAddress: z.optional(zReadCustomerAddressDto),
    deliveryAddressIsSame: z.boolean().register(z.globalRegistry, {
        description: 'Tell if delivery and billing address are deep equal or not'
    }),
    language: z.optional(z.string().register(z.globalRegistry, {
        description: 'Preferred language code'
    })),
    name: z.optional(z.string().register(z.globalRegistry, {
        description: 'Business name'
    })),
    commercialName: z.optional(z.string().register(z.globalRegistry, {
        description: 'Commercial/trading name'
    })),
    siren: z.optional(z.string().register(z.globalRegistry, {
        description: 'SIREN number'
    })),
    siret: z.optional(z.string().register(z.globalRegistry, {
        description: 'SIRET number'
    })),
    nafCode: z.optional(z.string().register(z.globalRegistry, {
        description: 'NAF/APE code'
    })),
    vatNumber: z.optional(z.string().register(z.globalRegistry, {
        description: 'VAT identification number'
    })),
    token: z.string().register(z.globalRegistry, {
        description: 'Customer token'
    }),
    tiersPrestationIsActivated: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Tiers prestation activation status'
    })),
    tiersPrestation: z.optional(zReadTiersPrestationDto),
    get parent() {
        return z.optional(z.lazy((): any => zReadCustomerDto));
    },
    contactId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Associated contact ID'
    })),
    organizationId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Associated organization ID'
    })),
    isDefault: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Default status flag'
    })),
    test: z.boolean().register(z.globalRegistry, {
        description: 'Test account flag'
    }),
    archivedAt: z.optional(z.number().register(z.globalRegistry, {
        description: 'Archived at'
    }))
});

export const zReadOpportunityDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'The opportunity ID'
    }),
    createdAt: z.number().register(z.globalRegistry, {
        description: 'The creation date as Unix timestamp'
    }),
    name: z.string().register(z.globalRegistry, {
        description: 'The name of the opportunity'
    }),
    description: z.optional(z.string().register(z.globalRegistry, {
        description: 'The description of the opportunity'
    })),
    dueDate: z.optional(z.number().register(z.globalRegistry, {
        description: 'The due date as Unix timestamp'
    })),
    amount: z.number().register(z.globalRegistry, {
        description: 'The amount in cents'
    }),
    rank: z.string().register(z.globalRegistry, {
        description: 'The rank for ordering'
    }),
    customerId: z.string().register(z.globalRegistry, {
        description: 'The legacy customer ID'
    }),
    categoryId: z.string().register(z.globalRegistry, {
        description: 'The category ID'
    }),
    category: zReadCategoryDto,
    customer: zReadCustomerDto
});

/**
 * The frequency at which reminders should be sent
 */
export const zReminderFrequency = z.enum(['on_due_date', 'every_week']).register(z.globalRegistry, {
    description: 'The frequency at which reminders should be sent'
});

export const zBillingReminderDto = z.object({
    inCopy: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if the sender should be in copy of the reminder'
    }),
    frequency: zReminderFrequency,
    numberOfRemindersToSend: z.number().register(z.globalRegistry, {
        description: 'The number of reminders to be sent'
    }),
    active: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if the reminder is active'
    }),
    recipients: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Array of email addresses to receive the reminder'
    }))
});

export const zReminderDto = z.object({
    inCopy: z.boolean(),
    frequency: zReminderFrequency,
    numberOfRemindersToSend: z.number(),
    active: z.boolean(),
    recipients: z.array(z.string())
});

export const zRentabilityPreferencesDto = z.object({
    defaultProductMargin: z.number().register(z.globalRegistry, {
        description: 'Marge par défaut pour les produits (en pourcentage)'
    }),
    defaultOverheadCosts: z.number().register(z.globalRegistry, {
        description: 'Coûts généraux par défaut (en pourcentage)'
    })
});

export const zPreferencesDto = z.object({
    rentability: zRentabilityPreferencesDto,
    notification: zNotificationPreferencesDto
});

export const zRetrieveCustomerPortalPaymentsDto = z.object({
    customer: zCustomerPortalCustomerDto,
    billings: z.array(zCustomerPortalBillingDto),
    company: zCustomerPortalCompanyDto,
    email: z.string(),
    phone: z.optional(z.string())
});

export const zSendBillingByEmailDto = z.object({
    emails: z.array(z.string()).max(10).register(z.globalRegistry, {
        description: 'List of email addresses to send the billing document to'
    }),
    subject: z.string().max(255).register(z.globalRegistry, {
        description: 'Email subject'
    }),
    content: z.string().register(z.globalRegistry, {
        description: 'Email content (HTML supported)'
    }),
    inCopy: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Whether to send a copy to the sender'
    })).default(false)
});

export const zSendTestEmailSignatureDto = z.object({
    content: z.optional(z.string())
});

export const zSetDefaultContactDto = z.object({
    defaultContactId: z.string()
});

export const zTiersPrestationDto = z.object({
    state: zClientState
});

export const zReadContactListItemDto = z.object({
    archivedAt: z.optional(z.number().register(z.globalRegistry, {
        description: 'Contact archival timestamp'
    })),
    createdAt: z.number().register(z.globalRegistry, {
        description: 'Contact creation timestamp'
    }),
    test: z.boolean().register(z.globalRegistry, {
        description: 'Whether this is a test contact'
    }),
    defaultContact: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Whether this is the default contact'
    })),
    emails: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Contact email addresses'
    })),
    hasBillings: z.boolean().register(z.globalRegistry, {
        description: 'Whether the contact has billings'
    }),
    id: z.string().register(z.globalRegistry, {
        description: 'Contact ID'
    }),
    fullname: z.string().register(z.globalRegistry, {
        description: 'Contact full name'
    }),
    organization: z.optional(zOrganizationDto),
    tiersPrestation: z.optional(zTiersPrestationDto)
});

export const zReadContactsDto = z.object({
    countWithoutFilters: z.number(),
    totalDocs: z.number(),
    limit: z.number(),
    totalPages: z.number(),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    nextPage: z.number(),
    page: z.number(),
    prevPage: z.number(),
    docs: z.array(zReadContactListItemDto)
});

export const zUpdateBillingBankInformationDto = z.object({
    bankInformation: z.union([
        zBankInformationDto,
        z.null()
    ])
});

export const zUpdateBillingCurrencyDto = z.object({
    currency: zCurrencyCode,
    currencyRate: z.optional(z.number().register(z.globalRegistry, {
        description: 'The conversion rate from the billing currency to the new currency'
    }))
});

export const zUpdateBillingDisplaySettingsDto = z.object({
    displayFullName: z.boolean().register(z.globalRegistry, {
        description: 'Afficher le nom complet'
    }),
    displayEmail: z.boolean().register(z.globalRegistry, {
        description: 'Afficher l\'email'
    }),
    displayPhoneNumber: z.boolean().register(z.globalRegistry, {
        description: 'Afficher le numéro de téléphone'
    }),
    displaySAPAgreement: z.boolean().register(z.globalRegistry, {
        description: 'Afficher l\'accord SAP'
    }),
    displayLegalStatus: z.boolean().register(z.globalRegistry, {
        description: 'Afficher le statut légal'
    }),
    displayRequiredMentionsProduct: z.boolean().register(z.globalRegistry, {
        description: 'Afficher les mentions obligatoires du produit'
    }),
    displayMemberOfAnApprovedAssociation: z.boolean().register(z.globalRegistry, {
        description: 'Afficher "Membre d\'une association agréée"'
    }),
    displayAbbyLogo: z.boolean().register(z.globalRegistry, {
        description: 'Afficher le logo Abby'
    }),
    displayTitle: z.boolean().register(z.globalRegistry, {
        description: 'Afficher le titre de la facture'
    }),
    displayGoodForApproval: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Afficher la mention bon pour accord'
    })),
    displayEstimateNumber: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Afficher le numéro du devis ou du bon de commande'
    }))
});

export const zUpdateBillingLocaleDto = z.object({
    locale: zBillingLocale
});

export const zUpdateContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.optional(z.string()),
    jobTitle: z.optional(z.string()),
    emails: z.optional(z.array(z.string())),
    billingAddress: z.optional(zClientAddressDto),
    deliveryAddress: z.optional(zClientAddressDto),
    bankInformations: z.optional(zBankInformationsDto),
    preferences: z.optional(zClientPreferencesDto)
});

export const zUpdateDeliveryAddressDto = z.object({
    line1: z.string().register(z.globalRegistry, {
        description: 'First line of address'
    }),
    line2: z.optional(z.string().register(z.globalRegistry, {
        description: 'Second line of address'
    })),
    city: z.string().register(z.globalRegistry, {
        description: 'City name'
    }),
    zipCode: z.string().register(z.globalRegistry, {
        description: 'Postal/ZIP code'
    }),
    country: zCountryCode
});

export const zUpdateBillingDeliveryAddressDto = z.object({
    deliveryAddress: z.union([
        zUpdateDeliveryAddressDto,
        z.null()
    ]),
    displayDeliveryAddress: z.boolean().register(z.globalRegistry, {
        description: 'Display delivery address'
    })
});

export const zUpdateEstimateAdvanceLinesDto = z.object({
    advances: z.array(zAdvanceItemDto).register(z.globalRegistry, {
        description: 'Array of advance items'
    })
});

export const zUpdateEstimateTimelineDto = z.object({
    emittedAt: z.number().register(z.globalRegistry, {
        description: 'The timestamp when the invoice was emitted'
    }),
    paymentDelay: zPaymentDelay,
    customDueDate: z.optional(z.number().register(z.globalRegistry, {
        description: 'Custom due date for the invoice when payment delay is OTHER'
    })),
    deliveryDate: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    expiredAt: z.number().register(z.globalRegistry, {
        description: 'The timestamp when the estimate expired'
    })
});

export const zUpdateInvoiceBankInformationDto = z.object({
    bankInformation: z.union([
        zBankInformationDto,
        z.null()
    ])
});

export const zUpdateInvoiceDeliveryAddressDto = z.object({
    deliveryAddress: z.union([
        zUpdateDeliveryAddressDto,
        z.null()
    ]),
    displayDeliveryAddress: z.boolean().register(z.globalRegistry, {
        description: 'Display delivery address'
    })
});

export const zUpdateInvoiceFrequencyDto = z.object({
    from: z.string(),
    to: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zUpdateInvoicePaymentRequestDto = z.object({
    paymentRequest: z.union([
        zPaymentRequestPayloadDto,
        z.null()
    ])
});

export const zUpdateInvoiceTimelineDto = z.object({
    emittedAt: z.number().register(z.globalRegistry, {
        description: 'The timestamp when the invoice was emitted'
    }),
    paymentDelay: zPaymentDelay,
    customDueDate: z.optional(z.number().register(z.globalRegistry, {
        description: 'Custom due date for the invoice when payment delay is OTHER'
    })),
    deliveryDate: z.optional(z.union([
        z.number(),
        z.null()
    ]))
});

export const zUpdateOpportunityDto = z.object({
    name: z.optional(z.string().register(z.globalRegistry, {
        description: 'The name of the opportunity'
    })),
    description: z.optional(z.string().register(z.globalRegistry, {
        description: 'The description of the opportunity (null to remove)'
    })),
    dueDate: z.optional(z.string().register(z.globalRegistry, {
        description: 'The due date as ISO date string YYYY-MM-DD (null to remove)'
    })),
    amount: z.optional(z.number().register(z.globalRegistry, {
        description: 'The amount in cents'
    })),
    customerId: z.optional(z.string().register(z.globalRegistry, {
        description: 'The legacy customer ID'
    })),
    categoryId: z.optional(z.string().register(z.globalRegistry, {
        description: 'The category ID'
    })),
    afterRank: z.optional(z.string().register(z.globalRegistry, {
        description: 'The rank to insert after'
    }))
});

export const zUpdateOrganizationContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.optional(z.string()),
    jobTitle: z.optional(z.string()),
    emails: z.optional(z.array(z.string())),
    notes: z.optional(z.string()),
    defaultContact: z.optional(z.boolean())
});

export const zUpdateOrganizationDto = z.object({
    name: z.string(),
    commercialName: z.optional(z.string()),
    emails: z.optional(z.array(z.string())),
    siret: z.optional(z.string()),
    vatNumber: z.optional(z.string()),
    billingAddress: z.optional(zClientAddressDto),
    deliveryAddress: z.optional(zClientAddressDto),
    bankInformations: z.optional(zBankInformationsDto),
    notes: z.optional(z.string()),
    preferences: z.optional(zClientPreferencesDto)
});

export const zUpdateTitleDto = z.object({
    title: z.union([
        z.string(),
        z.null()
    ])
});

export const zUserDto = z.object({
    id: z.string().register(z.globalRegistry, {
        description: 'Identifiant unique de l\'utilisateur'
    }),
    email: z.string().register(z.globalRegistry, {
        description: 'Adresse email de l\'utilisateur'
    }),
    firstname: z.string().register(z.globalRegistry, {
        description: 'Prénom de l\'utilisateur'
    }),
    lastname: z.string().register(z.globalRegistry, {
        description: 'Nom de l\'utilisateur'
    }),
    fullname: z.string().register(z.globalRegistry, {
        description: 'Nom complet de l\'utilisateur'
    }),
    firebaseToken: z.string().register(z.globalRegistry, {
        description: 'Token Firebase de l\'utilisateur'
    }),
    address: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zReadMeDto = z.object({
    company: zCompanyDto,
    preferences: zPreferencesDto,
    user: zUserDto
});

export const zVatCode = z.enum([
    'FR_210',
    'FR_550',
    'FR_850',
    'FR_1000',
    'FR_2000',
    'FR_00HT',
    'FR_00UE',
    'FR_0HUE'
]);

export const zReadBillingDetailsLineDto = z.object({
    generatedId: z.optional(z.string()),
    id: z.optional(z.string()),
    unitPrice: z.number(),
    productId: z.optional(z.string()),
    quantity: z.optional(z.number()),
    quantityUnit: z.optional(zProductUnit),
    designation: z.string(),
    reference: z.optional(z.string()),
    description: z.optional(z.string()),
    isDeliveryOfGoods: z.boolean(),
    type: z.optional(zProductType),
    vatCode: z.optional(zVatCode),
    personalServiceActivity: z.optional(zPersonalServiceActivity),
    priceWithoutTaxBeforeDiscount: z.number(),
    discountAmount: z.number(),
    discount: zDiscountLineDto,
    priceWithoutTaxAfterDiscount: z.number(),
    vatAmount: z.number(),
    priceTotalTax: z.number(),
    convertedAmounts: z.optional(zConvertedAmountsLineDto),
    isTaxIncluded: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Indicates whether the unit price includes tax (TTC) or excludes tax (HT)'
    }))
});

export const zUpdateLineDto = z.object({
    generatedId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Warning: Client-side generated line id. This field will be deprecated and will be removed in the future.'
    })),
    productId: z.optional(z.string().register(z.globalRegistry, {
        description: 'Unique identifier of the product, if applicable'
    })),
    unitPrice: z.number().register(z.globalRegistry, {
        description: 'Price per unit in cents (e.g., 1500 for 15.00 euros)'
    }),
    quantity: z.number().register(z.globalRegistry, {
        description: 'Quantity of the product or service'
    }),
    quantityUnit: z.union([
        zProductUnit,
        z.null()
    ]),
    designation: z.string().register(z.globalRegistry, {
        description: 'Name or short description of the product or service'
    }),
    reference: z.optional(z.string().register(z.globalRegistry, {
        description: 'Product reference or SKU, if applicable'
    })),
    description: z.optional(z.string().register(z.globalRegistry, {
        description: 'Detailed description of the product or service'
    })),
    type: z.union([
        zProductType,
        z.null()
    ]),
    vatCode: zVatCode,
    personalServiceActivity: z.optional(zPersonalServiceActivity),
    discount: z.optional(zDiscountDto),
    isDeliveryOfGoods: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Mark a product line as delivery of goods to display it on document'
    })),
    isTaxIncluded: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Indicates whether the unit price includes tax (TTC) or excludes tax (HT)'
    })).default(false)
});

export const zUpdateBillingLinesDto = z.object({
    lines: z.array(zUpdateLineDto).register(z.globalRegistry, {
        description: 'Array of billing lines, each representing a product or service'
    }),
    discount: z.optional(zDiscountDto)
});

export const zVatDetailDto = z.object({
    vatCode: zVatCode,
    amount: z.number(),
    vatRate: z.number()
});

export const zConvertedAmountsDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingAmountToBill: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.optional(z.number()),
    billedAmountWithoutTax: z.number(),
    billedAmountWithTax: z.number(),
    remainingAmountWithoutTaxWithoutDisbursement: z.number(),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number()
});

export const zEstimateTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingAmountToBill: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.optional(z.number()),
    convertedAmounts: z.optional(zConvertedAmountsDto),
    billedAmountWithoutTax: z.number(),
    billedAmountWithTax: z.number(),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number(),
    remainingAmountWithoutTaxWithoutDisbursement: z.number()
});

export const zReadInvoiceTotalWithoutConvertedAmountsDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    discountAmount: z.optional(z.number()),
    vatDetails: z.array(zVatDetailDto),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number()
});

export const zReadInvoiceTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    discountAmount: z.optional(z.number()),
    vatDetails: z.array(zVatDetailDto),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number(),
    convertedAmounts: z.optional(zReadInvoiceTotalWithoutConvertedAmountsDto)
});

export const zTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.optional(z.number()),
    convertedAmounts: z.optional(zConvertedAmountsDto)
});

export const zVatMention = z.enum([
    'not_subject',
    'second_hand_good',
    'art_object',
    'collection_antique',
    'travel_agency',
    'vat_not_applicable',
    'vat_not_applicable_2',
    'vat_exemption',
    'vat_exemption_eu_sale',
    'vat_exemption_eu_service',
    'vat_construction',
    'vat_psychologist',
    'vat_psychologist_2',
    'vat_reverse_charge',
    'vat_reverse_charge_2',
    'vat_reverse_charge_3',
    'vat_reverse_charge_4',
    'vat_reduced_rate',
    'vat_reduced_rate_2',
    'vat_article_261c_cgi',
    'vat_exemption_294_cgi'
]);

export const zBillingLegalsDto = z.object({
    headerNote: z.optional(z.string()),
    footerNote: z.optional(z.string()),
    generalTermsAndConditionsOfSale: z.optional(z.string()),
    mentionMediator: z.optional(z.string()),
    vatMention: zVatMention,
    paymentMethods: z.array(zPaymentMethod),
    otherPaymentMethod: z.optional(z.string().register(z.globalRegistry, {
        description: 'Other payment method'
    }))
});

export const zUpdateAdvanceGeneralInformationsDto = z.object({
    headerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the header of the billing'
    })),
    footerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the footer of the billing'
    })),
    generalTermsAndConditionsOfSale: z.optional(z.string().register(z.globalRegistry, {
        description: 'General terms and conditions of sale to be included in the billing'
    })),
    mentionMediator: z.optional(z.string().register(z.globalRegistry, {
        description: 'Mention mediateur to be included in the billing'
    })),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Array of accepted payment methods for the billing'
    })),
    otherPaymentMethod: z.optional(z.string().register(z.globalRegistry, {
        description: 'Other payment method'
    })),
    vatMention: z.optional(zVatMention),
    latePenalty: z.optional(z.union([
        zBillingLatePenaltyDto,
        z.null()
    ])),
    lumpSumCompensation: z.optional(z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ])),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    isOnlinePaymentActivated: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Indicates if online payment is activated for this invoice'
    })),
    reminder: z.optional(zBillingReminderDto)
});

export const zUpdateAssetGeneralInformationsDto = z.object({
    headerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the header of the billing'
    })),
    footerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the footer of the billing'
    })),
    generalTermsAndConditionsOfSale: z.optional(z.string().register(z.globalRegistry, {
        description: 'General terms and conditions of sale to be included in the billing'
    })),
    mentionMediator: z.optional(z.string().register(z.globalRegistry, {
        description: 'Mention mediateur to be included in the billing'
    })),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Array of accepted payment methods for the billing'
    })),
    otherPaymentMethod: z.optional(z.string().register(z.globalRegistry, {
        description: 'Other payment method'
    })),
    vatMention: z.optional(zVatMention),
    latePenalty: z.optional(z.union([
        zBillingLatePenaltyDto,
        z.null()
    ])),
    lumpSumCompensation: z.optional(z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ])),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]))
});

export const zUpdateEstimateGeneralInformationsDto = z.object({
    headerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the header of the billing'
    })),
    footerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the footer of the billing'
    })),
    generalTermsAndConditionsOfSale: z.optional(z.string().register(z.globalRegistry, {
        description: 'General terms and conditions of sale to be included in the billing'
    })),
    mentionMediator: z.optional(z.string().register(z.globalRegistry, {
        description: 'Mention mediateur to be included in the billing'
    })),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Array of accepted payment methods for the billing'
    })),
    otherPaymentMethod: z.optional(z.string().register(z.globalRegistry, {
        description: 'Other payment method'
    })),
    vatMention: z.optional(zVatMention),
    latePenalty: z.optional(z.union([
        zBillingLatePenaltyDto,
        z.null()
    ])),
    lumpSumCompensation: z.optional(z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ])),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]))
});

export const zUpdateInvoiceGeneralInformationsDto = z.object({
    headerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the header of the billing'
    })),
    footerNote: z.optional(z.string().register(z.globalRegistry, {
        description: 'Custom note to be displayed in the footer of the billing'
    })),
    generalTermsAndConditionsOfSale: z.optional(z.string().register(z.globalRegistry, {
        description: 'General terms and conditions of sale to be included in the billing'
    })),
    mentionMediator: z.optional(z.string().register(z.globalRegistry, {
        description: 'Mention mediateur to be included in the billing'
    })),
    paymentMethods: z.optional(z.array(z.string()).register(z.globalRegistry, {
        description: 'Array of accepted payment methods for the billing'
    })),
    otherPaymentMethod: z.optional(z.string().register(z.globalRegistry, {
        description: 'Other payment method'
    })),
    vatMention: z.optional(zVatMention),
    latePenalty: z.optional(z.union([
        zBillingLatePenaltyDto,
        z.null()
    ])),
    lumpSumCompensation: z.optional(z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ])),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    isOnlinePaymentActivated: z.optional(z.boolean().register(z.globalRegistry, {
        description: 'Indicates if online payment is activated for this invoice'
    })),
    reminder: z.optional(zBillingReminderDto)
});

export const zReadAdvanceDto = z.object({
    id: z.string(),
    number: z.optional(z.string()),
    title: z.optional(z.string().register(z.globalRegistry, {
        description: 'Title of the billing document'
    })),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.optional(z.number()),
    opportunity: z.optional(zOpportunityDto),
    locked: z.optional(z.boolean()),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.optional(z.number()),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: z.optional(zReadBankInformationDto),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.optional(z.number()),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.optional(z.number()),
    lastSendByEmailAt: z.optional(z.number()),
    paymentDelay: zPaymentDelay,
    dueAt: z.optional(z.number()),
    paidAt: z.optional(z.number()),
    lastReminderSentAt: z.optional(z.number()),
    isReminderActivated: z.boolean(),
    designation: z.string(),
    isOnlinePaymentActivated: z.boolean(),
    description: z.optional(z.string()),
    total: zTotalDto,
    discount: z.optional(zDiscountDto),
    displaySettings: zDisplaySettingsDto,
    get parent() {
        return z.optional(z.lazy((): any => zReadEstimateDto));
    },
    advanceMode: zAdvanceMode,
    advancePercentage: z.number(),
    advanceAmount: z.number(),
    reminder: z.optional(zBillingReminderDto),
    latePenalty: z.optional(zBillingLatePenaltyDto),
    lumpSumCompensation: z.optional(zBillingLumpSumCompensationDto),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    hasAssociatedTransaction: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if the customer has an associated transaction'
    }),
    includeDisbursement: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if the advance includes disbursement'
    }),
    canceledAt: z.optional(z.number())
});

export const zReadAssetDto = z.object({
    id: z.string(),
    number: z.optional(z.string()),
    title: z.optional(z.string().register(z.globalRegistry, {
        description: 'Title of the billing document'
    })),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.optional(z.number()),
    opportunity: z.optional(zOpportunityDto),
    locked: z.optional(z.boolean()),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.optional(z.number()),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: z.optional(zReadBankInformationDto),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.optional(z.number()),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.optional(z.number()),
    lastSendByEmailAt: z.optional(z.number()),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zReadInvoiceTotalDto,
    discount: z.optional(zDiscountDto),
    parent: z.optional(z.union([
        z.lazy((): any => zReadInvoiceDto),
        zReadAdvanceDto
    ])),
    refundAt: z.optional(z.number()),
    latePenalty: z.optional(z.union([
        zBillingLatePenaltyDto,
        z.null()
    ])),
    lumpSumCompensation: z.optional(z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ])),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    displaySettings: zDisplayBillingSettingsDto,
    dueAt: z.optional(z.number()),
    paymentDelay: zPaymentDelay,
    includeDiscountDisbursement: z.boolean()
});

export const zReadEstimateDto = z.object({
    id: z.string(),
    number: z.optional(z.string()),
    title: z.optional(z.string().register(z.globalRegistry, {
        description: 'Title of the billing document'
    })),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.optional(z.number()),
    opportunity: z.optional(zOpportunityDto),
    locked: z.optional(z.boolean()),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.optional(z.number()),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: z.optional(zReadBankInformationDto),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.optional(z.number()),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.optional(z.number()),
    lastSendByEmailAt: z.optional(z.number()),
    paymentDelay: zPaymentDelay,
    expiredAt: z.number(),
    refusedAt: z.optional(z.number()),
    signedAt: z.optional(z.number()),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zEstimateTotalDto,
    discount: z.optional(zDiscountDto),
    latePenalty: z.optional(zLatePenaltyDto),
    lumpSumCompensation: z.optional(zLumpSumCompensationDto),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    displaySettings: zDisplaySettingsDto,
    advances: z.array(zReadAdvanceDto),
    advanceEstimateLines: zReadEstimateAdvanceLinesDto,
    withElectronicSignature: z.boolean(),
    electronicSignature: zEstimateElectronicSignatureDto,
    dueAt: z.optional(z.number()),
    electronicSignatureRequirements: z.array(zElectronicSignatureRequirementDto),
    hasFinalInvoice: z.boolean(),
    includeDiscountDisbursement: z.boolean()
});

export const zReadInvoiceDto = z.object({
    id: z.string(),
    number: z.optional(z.string()),
    title: z.optional(z.string().register(z.globalRegistry, {
        description: 'Title of the billing document'
    })),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.optional(z.number()),
    opportunity: z.optional(zOpportunityDto),
    locked: z.optional(z.boolean()),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.optional(z.number()),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: z.optional(zReadBankInformationDto),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.optional(z.number()),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.optional(z.number()),
    lastSendByEmailAt: z.optional(z.number()),
    paymentDelay: zPaymentDelay,
    dueAt: z.number(),
    paidAt: z.optional(z.number()),
    lastReminderSentAt: z.optional(z.number()),
    isReminderActivated: z.boolean(),
    isOnlinePaymentActivated: z.boolean(),
    isFinalInvoice: z.boolean(),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zReadInvoiceTotalDto,
    reminder: z.optional(zReminderDto),
    discount: z.optional(zDiscountDto),
    latePenalty: z.optional(zLatePenaltyDto),
    lumpSumCompensation: z.optional(zBillingLumpSumCompensationDto),
    discountAdvancePayment: z.optional(z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ])),
    displaySettings: zDisplayBillingSettingsDto,
    paymentRequest: z.optional(z.union([
        zPaymentRequestDto,
        z.null()
    ])),
    parent: z.optional(zReadEstimateDto),
    frequency: z.optional(zFrequencyDto),
    hasAssociatedTransaction: z.boolean().register(z.globalRegistry, {
        description: 'Indicates if the customer has an associated transaction'
    }),
    includeDiscountDisbursement: z.boolean(),
    expiredAt: z.optional(z.number()),
    canceledAt: z.optional(z.number())
});

export const zBillingControllerDownloadPdfData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        billingId: z.string()
    }),
    query: z.optional(z.object({
        locale: z.optional(zBillingLocale)
    }))
});

export const zBillingControllerDeleteBillingDocumentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentId: z.string().register(z.globalRegistry, {
            description: 'ID of the document to delete'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerSendTestEmailSignatureData = z.object({
    body: zSendTestEmailSignatureDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zBillingControllerRenderEmailData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to render'
        }),
        emailType: zBillingEmailType
    }),
    query: z.optional(z.never())
});

export const zBillingControllerSendEmailTestData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to send the email test'
        }),
        emailType: zBillingEmailType
    }),
    query: z.optional(z.never())
});

export const zBillingControllerSendByEmailData = z.object({
    body: zSendBillingByEmailDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing document to send'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerRetrievePaymentAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCustomerPortalControllerGetPaymentsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zContactControllerCreateContactData = z.object({
    body: zCreateContactDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zContactControllerDeleteContactData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zContactControllerGetContactData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zContactControllerUpdateContactData = z.object({
    body: zUpdateContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zContactControllerGetContactByLegacyIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        legacyId: z.string()
    }),
    query: z.optional(z.never())
});

export const zContactsControllerRetrieveContactsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.number()),
        limit: z.optional(z.number()),
        search: z.optional(z.string()),
        orderBy: z.optional(zContactOrderBy),
        orderDirection: z.optional(zOrderDirection),
        archived: z.optional(z.boolean()),
        forCertificate: z.optional(z.boolean())
    }))
});

export const zOrganizationControllerCreateOrganizationData = z.object({
    body: zCreateOrganizationDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zOrganizationControllerRetrieveOrganizationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerUpdateOrganizationData = z.object({
    body: zUpdateOrganizationDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerRetrieveOrganizationContactsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerCreateOrganizationContactData = z.object({
    body: zCreateOrganizationContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerUpdateOrganizationContactData = z.object({
    body: zUpdateOrganizationContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerDeleteOrganizationData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        organizationId: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationControllerSetDefaultContactData = z.object({
    body: zSetDefaultContactDto,
    path: z.object({
        organizationId: z.string()
    }),
    query: z.optional(z.never())
});

export const zOrganizationsControllerRetrieveOrganizationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        page: z.number(),
        limit: z.number(),
        search: z.optional(z.string()),
        orderBy: z.optional(zOrganizationOrderBy),
        orderDirection: z.optional(zOrderDirection),
        archived: z.optional(z.boolean())
    })
});

export const zOpportunityControllerRetrieveCategoriesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zOpportunityControllerDeleteOpportunityData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOpportunityControllerRetrieveOpportunityData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOpportunityControllerUpdateOpportunityData = z.object({
    body: zUpdateOpportunityDto,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zOpportunityControllerCreateOpportunityData = z.object({
    body: zCreateOpportunityDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCompanyControllerGetMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zEstimateControllerCreateEstimateByContactOrOrganizationIdData = z.object({
    body: zCreateEstimateByCustomerIdDto,
    path: z.object({
        customerId: z.string()
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUpdateTimelineData = z.object({
    body: zUpdateEstimateTimelineDto,
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerSignData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate or purchase order to sign'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUnsignData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate or purchase order to unsign'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerRefuseData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate or purchase order to refuse'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUnrefuseData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate or purchase order to unrefuse'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerCreateAdvanceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateEstimateGeneralInformationsDto,
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUpdateLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUpdateCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zEstimateControllerUpdateAdvanceLinesData = z.object({
    body: zUpdateEstimateAdvanceLinesDto,
    path: z.object({
        estimateId: z.string().register(z.globalRegistry, {
            description: 'ID of the estimate to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerGetInvoiceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to retrieve'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerCreateInvoiceByContactOrOrganizationIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        customerId: z.string()
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceLinesData = z.object({
    body: zUpdateBillingLinesDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceDeliveryAddressData = z.object({
    body: zUpdateInvoiceDeliveryAddressDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateTimelineData = z.object({
    body: zUpdateInvoiceTimelineDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoicePaymentRequestData = z.object({
    body: zUpdateInvoicePaymentRequestDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerFinalizeInvoiceData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to finalize'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceGeneralInformationsData = z.object({
    body: zUpdateInvoiceGeneralInformationsDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateDisplaySettingsData = z.object({
    body: zUpdateBillingDisplaySettingsDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID de la facture à mettre à jour'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceBankInformationData = z.object({
    body: zUpdateInvoiceBankInformationDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerDeleteInvoiceFrequencyData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerCreateInvoiceFrequencyData = z.object({
    body: zCreateInvoiceFrequencyDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerUpdateInvoiceFrequencyData = z.object({
    body: zUpdateInvoiceFrequencyDto,
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        }),
        frequencyId: z.unknown().register(z.globalRegistry, {
            description: 'ID of the frequency to update'
        })
    }),
    query: z.optional(z.never())
});

export const zInvoiceControllerCreateAssetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        invoiceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to create asset from'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerArchiveBillingDocumentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentId: z.string().register(z.globalRegistry, {
            description: 'ID of the document to archive'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUnarchiveBillingDocumentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentId: z.string().register(z.globalRegistry, {
            description: 'ID of the document to unarchive'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUpdateTitleData = z.object({
    body: zUpdateTitleDto,
    path: z.object({
        documentId: z.string().register(z.globalRegistry, {
            description: 'ID of the document to update title'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerGetBillingByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing document'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUpdateBankInformationData = z.object({
    body: zUpdateBillingBankInformationDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to update'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUpdateBillingDeliveryAddressData = z.object({
    body: zUpdateBillingDeliveryAddressDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to update'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerFinalizeData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to finalize'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUpdateLinesData = z.object({
    body: zUpdateBillingLinesDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to update'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerMigrateSapProductsData = z.object({
    body: zMigrateSapProductsDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to update'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerToggleIncludeDiscountDisbursementData = z.object({
    body: z.object({
        includeDiscountDisbursement: z.optional(z.boolean())
    }),
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing to update'
        })
    }),
    query: z.optional(z.never())
});

export const zBillingControllerUpdateDisplaySettingsData = z.object({
    body: zUpdateBillingDisplaySettingsDto,
    path: z.object({
        billingId: z.string().register(z.globalRegistry, {
            description: 'ID of the billing document to update'
        })
    }),
    query: z.optional(z.never())
});

export const zAdvanceControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateAdvanceGeneralInformationsDto,
    path: z.object({
        advanceId: z.string().register(z.globalRegistry, {
            description: 'ID of the advance to update'
        })
    }),
    query: z.optional(z.never())
});

export const zAdvanceControllerCreateAssetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        advanceId: z.string().register(z.globalRegistry, {
            description: 'ID of the invoice to create asset from'
        })
    }),
    query: z.optional(z.never())
});

export const zAssetControllerGetAssetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        assetId: z.string().register(z.globalRegistry, {
            description: 'ID of the asset to retrieve'
        })
    }),
    query: z.optional(z.never())
});

export const zAssetControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateAssetGeneralInformationsDto,
    path: z.object({
        assetId: z.string().register(z.globalRegistry, {
            description: 'ID of the asset to update'
        })
    }),
    query: z.optional(z.never())
});

export const zAssetControllerUpdateLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        assetId: z.string().register(z.globalRegistry, {
            description: 'ID of the asset to update'
        })
    }),
    query: z.optional(z.never())
});

export const zAssetControllerUpdateCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        assetId: z.string().register(z.globalRegistry, {
            description: 'ID of the asset to update'
        })
    }),
    query: z.optional(z.never())
});
