// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * The mode of the advance (amount or percentage)
 */
export const zAdvanceMode = z.enum(['AMOUNT', 'PERCENTAGE']).describe('The mode of the advance (amount or percentage)');

export const zAdvanceItemDto = z.object({
    value: z.number().describe('The value of the advance (amount or percentage)'),
    mode: zAdvanceMode,
    paymentCondition: z.enum([
        'SIGNATURE',
        'ORDER',
        'OTHER'
    ]).describe('Payment condition for the advance').optional(),
    customPaymentCondition: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zBankInformationDto = z.object({
    bic: z.string(),
    iban: z.string(),
    holder: z.string()
});

export const zBankInformationsDto = z.object({
    iban: z.string().describe('International Bank Account Number'),
    bic: z.string().describe('Bank Identifier Code'),
    holder: z.string().describe('Name of the account holder')
});

export const zBillingCompatibilityVersion = z.enum(['V1', 'V2']);

export const zBillingEmailType = z.enum([
    'invoice_simple',
    'invoice_reminder',
    'invoice_recurring',
    'estimate_simple'
]);

export const zBillingLocale = z.enum([
    'fr',
    'en',
    'de',
    'it',
    'nl',
    'pt',
    'es'
]);

export const zBillingState = z.enum([
    'draft',
    'finalized',
    'signed',
    'refused',
    'paid'
]);

export const zBillingType = z.enum([
    'estimate',
    'invoice',
    'asset',
    'advance',
    'purchase_order'
]);

/**
 * Current client state
 */
export const zClientState = z.enum([
    'synced',
    'pending',
    'end_user_action_required',
    'error'
]).describe('Current client state');

export const zContactOrderBy = z.enum(['name', 'createdAt']);

export const zConvertedAmountsLineDto = z.object({
    priceWithoutTaxBeforeDiscount: z.number(),
    discountAmount: z.number().optional(),
    priceWithoutTaxAfterDiscount: z.number(),
    vatAmount: z.number(),
    priceTotalTax: z.number()
});

/**
 * Country code of the address
 */
export const zCountryCode = z.enum([
    'AF',
    'AX',
    'AL',
    'DZ',
    'AS',
    'AD',
    'AO',
    'AI',
    'AQ',
    'AG',
    'AN',
    'AR',
    'AM',
    'AW',
    'AU',
    'AT',
    'AZ',
    'BS',
    'BH',
    'BD',
    'BB',
    'BY',
    'BE',
    'BZ',
    'BJ',
    'BM',
    'BT',
    'BO',
    'BQ',
    'BA',
    'BW',
    'BV',
    'BR',
    'IO',
    'BN',
    'BG',
    'BF',
    'BI',
    'KH',
    'CM',
    'CA',
    'CV',
    'KY',
    'CF',
    'TD',
    'CL',
    'CN',
    'CX',
    'CC',
    'CO',
    'KM',
    'CG',
    'CD',
    'CK',
    'CR',
    'CI',
    'HR',
    'CU',
    'CW',
    'CY',
    'CZ',
    'DK',
    'DJ',
    'DM',
    'DO',
    'EC',
    'EG',
    'SV',
    'GQ',
    'ER',
    'EE',
    'ET',
    'FK',
    'FO',
    'FJ',
    'FI',
    'FR',
    'GF',
    'PF',
    'TF',
    'GA',
    'GM',
    'GE',
    'DE',
    'GH',
    'GI',
    'GR',
    'GL',
    'GD',
    'GP',
    'GU',
    'GT',
    'GG',
    'GN',
    'GW',
    'GY',
    'HT',
    'HM',
    'VA',
    'HN',
    'HK',
    'HU',
    'IS',
    'IN',
    'ID',
    'IR',
    'IQ',
    'IE',
    'IM',
    'IL',
    'IT',
    'JM',
    'JP',
    'JE',
    'JO',
    'KZ',
    'KE',
    'KI',
    'KR',
    'XK',
    'KP',
    'KW',
    'KG',
    'LA',
    'LV',
    'LB',
    'LS',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MK',
    'MG',
    'MW',
    'MY',
    'MV',
    'ML',
    'MT',
    'MH',
    'MQ',
    'MR',
    'MU',
    'YT',
    'MX',
    'FM',
    'MD',
    'MC',
    'MN',
    'ME',
    'MS',
    'MA',
    'MZ',
    'MM',
    'NA',
    'NR',
    'NP',
    'NL',
    'NC',
    'NZ',
    'NI',
    'NE',
    'NG',
    'NU',
    'NF',
    'MP',
    'NO',
    'OM',
    'PK',
    'PW',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PN',
    'PL',
    'PT',
    'PR',
    'QA',
    'RE',
    'RO',
    'RU',
    'RW',
    'BL',
    'SH',
    'KN',
    'LC',
    'MF',
    'PM',
    'VC',
    'WS',
    'SM',
    'ST',
    'SA',
    'SN',
    'RS',
    'SC',
    'SL',
    'SG',
    'SX',
    'SK',
    'SI',
    'SB',
    'SO',
    'ZA',
    'GS',
    'SS',
    'ES',
    'LK',
    'SD',
    'SR',
    'SJ',
    'SZ',
    'SE',
    'CH',
    'SY',
    'TW',
    'TJ',
    'TZ',
    'TH',
    'TL',
    'TG',
    'TK',
    'TO',
    'TT',
    'TN',
    'TR',
    'TM',
    'TC',
    'TV',
    'UG',
    'UA',
    'AE',
    'GB',
    'US',
    'UM',
    'UY',
    'UZ',
    'VU',
    'VE',
    'VN',
    'VG',
    'VI',
    'WF',
    'EH',
    'YE',
    'ZM',
    'ZW'
]).describe('Country code of the address');

export const zAddressDto = z.object({
    line1: z.string().describe('First line of the address'),
    line2: z.string().describe('Second line of the address').optional(),
    city: z.string().describe('City of the address'),
    zipCode: z.string().describe('Zip code of the address'),
    country: zCountryCode
});

export const zClientAddressDto = z.object({
    address: z.union([
        z.string(),
        z.null()
    ]),
    complement: z.union([
        z.string(),
        z.null()
    ]).optional(),
    city: z.union([
        z.string(),
        z.null()
    ]),
    zipCode: z.union([
        z.string(),
        z.null()
    ]),
    state: z.string().describe('The state or province of the address').optional(),
    country: zCountryCode
});

export const zCreateOpportunityDto = z.object({
    name: z.string().describe('The name of the opportunity'),
    description: z.string().describe('The description of the opportunity').optional(),
    dueDate: z.string().describe('The due date as ISO date string YYYY-MM-DD').optional(),
    amount: z.number().describe('The amount in cents'),
    customerId: z.string().describe('The legacy customer ID'),
    categoryId: z.string().describe('The category ID'),
    afterRank: z.string().describe('The rank to insert after').optional()
});

export const zCreateOrganizationContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.string().optional(),
    jobTitle: z.string().optional(),
    emails: z.array(z.string()).optional(),
    notes: z.string().optional()
});

export const zCurrencyCode = z.enum([
    'EUR',
    'GBP',
    'CHF',
    'USD',
    'AUD',
    'CAD',
    'JPY',
    'CNH',
    'CZK',
    'DKK',
    'BGN',
    'PLN',
    'HUF',
    'RON',
    'SEK',
    'NOK',
    'TRY',
    'BRL',
    'HKD',
    'ILS',
    'INR',
    'KRW',
    'MXN'
]);

export const zClientPreferencesDto = z.object({
    language: zBillingLocale.optional(),
    currency: zCurrencyCode.optional(),
    paymentMethods: z.array(z.string()).describe('The client\'s preferred payment methods').optional()
});

export const zCreateContactDto = z.object({
    firstname: z.string().describe('The first name of the contact'),
    lastname: z.string().describe('The last name of the contact'),
    phone: z.string().describe('The phone number of the contact').optional(),
    jobTitle: z.string().describe('The job title of the contact').optional(),
    emails: z.array(z.string()).describe('The email addresses of the contact').optional(),
    notes: z.string().describe('Additional notes about the contact').optional(),
    billingAddress: zClientAddressDto.optional(),
    deliveryAddress: zClientAddressDto.optional(),
    bankInformations: zBankInformationsDto.optional(),
    preferences: zClientPreferencesDto.optional()
});

export const zCreateOrganizationDto = z.object({
    name: z.string().describe('The official name of the organization'),
    commercialName: z.string().describe('The commercial or trading name of the organization').optional(),
    emails: z.array(z.string()).optional(),
    siret: z.string().describe('The SIRET number (required for French organizations)').optional(),
    vatNumber: z.string().describe('The VAT number of the organization').optional(),
    billingAddress: zClientAddressDto.optional(),
    deliveryAddress: zClientAddressDto.optional(),
    notes: z.string().describe('Additional notes about the organization').optional(),
    bankInformations: zBankInformationsDto.optional(),
    preferences: zClientPreferencesDto.optional()
});

export const zCurrencyOrigin = z.enum(['ECB', 'USER']);

export const zCustomerPortalBillingDto = z.object({
    id: z.string(),
    number: z.string(),
    date: z.number(),
    billingState: zBillingState,
    billingType: zBillingType,
    amount: z.number(),
    signatureId: z.string().optional(),
    signature: z.record(z.unknown()).optional(),
    dueDate: z.number().optional(),
    validityDate: z.number().optional()
});

export const zCustomerPortalCompanyDto = z.object({
    commercialName: z.string(),
    name: z.string()
});

export const zCustomerPortalCustomerDto = z.object({
    name: z.string(),
    firstname: z.string().optional(),
    lastname: z.string().optional()
});

/**
 * Type de remise sur acompte
 */
export const zDiscountAdvancePayment = z.enum(['none', 'other']).describe('Type de remise sur acompte');

export const zBillingDiscountAdvancePaymentDto = z.object({
    value: zDiscountAdvancePayment,
    otherValue: z.string().describe('Description custom si `value` vaut `other`').optional()
});

/**
 * Mode de la réduction en pourcentage ou en euros
 */
export const zDiscountMode = z.enum(['PERCENTAGE', 'AMOUNT']).describe('Mode de la réduction en pourcentage ou en euros');

export const zDiscountDto = z.object({
    mode: zDiscountMode,
    amount: z.number().describe('The amount for the discount (1000 for 10% or 10€)')
});

export const zDiscountLineDto = z.object({
    amount: z.number().describe('Montant de la remise, 1000 pour 10% ou 10€'),
    mode: zDiscountMode
});

export const zDisplayBillingSettingsDto = z.object({
    displayFullName: z.boolean(),
    displayEmail: z.boolean(),
    displayPhoneNumber: z.boolean(),
    displaySAPAgreement: z.boolean(),
    displayLegalStatus: z.boolean(),
    displayRequiredMentionsProduct: z.boolean(),
    displayMemberOfAnApprovedAssociation: z.boolean(),
    displayAbbyLogo: z.boolean(),
    displayTitle: z.boolean(),
    displayGoodForApproval: z.boolean().optional(),
    displayEstimateNumber: z.boolean().optional()
});

export const zDisplaySettingsDto = z.object({
    displayFullName: z.boolean(),
    displayEmail: z.boolean(),
    displayPhoneNumber: z.boolean(),
    displaySAPAgreement: z.boolean(),
    displayLegalStatus: z.boolean(),
    displayRequiredMentionsProduct: z.boolean(),
    displayGoodForApproval: z.boolean().optional(),
    displayMemberOfAnApprovedAssociation: z.boolean(),
    displayAbbyLogo: z.boolean(),
    displayTitle: z.boolean()
});

export const zElectronicSignatureRequirementDto = z.object({
    name: z.string(),
    message: z.string()
});

export const zElectronicSignatureStatus = z.enum([
    'requested',
    'activated',
    'on_going',
    'refused',
    'signed',
    'cancelled'
]);

export const zEstimateElectronicSignatureDto = z.object({
    id: z.string(),
    canceledAt: z.union([
        z.number(),
        z.null()
    ]),
    procedureId: z.union([
        z.string(),
        z.null()
    ]),
    magicLink: z.union([
        z.string(),
        z.null()
    ]),
    signedAt: z.union([
        z.number(),
        z.null()
    ]),
    refusedAt: z.union([
        z.number(),
        z.null()
    ]),
    status: zElectronicSignatureStatus
});

export const zEstimateType = z.enum(['estimate', 'purchase_order']);

export const zCreateEstimateByCustomerIdDto = z.object({
    estimateType: zEstimateType.optional()
});

export const zFinalizeRequirementDto = z.object({
    name: z.string(),
    message: z.string()
});

export const zFrequencyInterval = z.enum([
    'day',
    'week',
    'month',
    'year'
]);

export const zCreateInvoiceFrequencyDto = z.object({
    from: z.string(),
    to: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zFrequencyDto = z.object({
    id: z.string(),
    from: z.string(),
    to: z.string(),
    nextBillingAt: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zLatePenalty = z.enum([
    'three_time_legal_rate',
    'bce_director_rate_plus_ten_points',
    'other'
]);

export const zBillingLatePenaltyDto = z.object({
    value: zLatePenalty,
    otherValue: z.string().describe('Description custom si `value` vaut `other`').optional()
});

export const zLatePenaltyDto = z.object({
    value: zLatePenalty,
    otherValue: z.string().describe('Description custom si `value` vaut `other`').optional()
});

export const zLegalStatus = z.enum([
    'micro_enterprise',
    'sas',
    'sarl',
    'sasu',
    'ei',
    'eurl',
    'eirl',
    'sa',
    'snc',
    'other',
    'sasu_sas',
    'eurl_sarl',
    'sci',
    'association'
]);

export const zCompanyDto = z.object({
    id: z.string().describe('Identifiant unique de l\'entreprise'),
    commercialName: z.string().describe('Nom commercial de l\'entreprise'),
    siret: z.string().describe('Numéro SIRET de l\'entreprise'),
    legalStatut: zLegalStatus,
    address: z.string().describe('Adresse de l\'entreprise'),
    city: z.string().describe('Ville de l\'entreprise'),
    isInTestMode: z.boolean().describe('Indique si l\'entreprise est en mode test')
});

export const zLumpSumCompensation = z.enum(['forty_euros', 'other']);

export const zBillingLumpSumCompensationDto = z.object({
    value: zLumpSumCompensation,
    otherValue: z.string().describe('Description custom si `value` vaut `other`').optional()
});

export const zLumpSumCompensationDto = z.object({
    value: zLumpSumCompensation,
    otherValue: z.string().describe('Description custom si `value` vaut `other`').optional()
});

export const zOpportunityDto = z.object({
    id: z.string(),
    name: z.string()
});

export const zOrderDirection = z.enum(['ASC', 'DESC']);

export const zOrganizationDto = z.object({
    id: z.string().describe('Organization ID'),
    name: z.string().describe('Organization name')
});

export const zOrganizationOrderBy = z.enum(['name', 'createdAt']);

/**
 * The reason of the payment account
 */
export const zPaymentAccountIssueReason = z.enum([
    'MISSING_INFO',
    'UNDER_REVIEW',
    'FRAUD_SUSPECTED',
    'TERMS_VIOLATION',
    'UNKNOWN'
]).describe('The reason of the payment account');

/**
 * The status of the payment account
 */
export const zPaymentAccountStatus = z.enum(['enabled', 'disabled']).describe('The status of the payment account');

/**
 * Payment condition for the advance
 */
export const zPaymentCondition = z.enum([
    'SIGNATURE',
    'ORDER',
    'OTHER'
]).describe('Payment condition for the advance');

export const zPaymentDelay = z.enum([
    'at_reception',
    'end_of_month',
    'seven_days',
    'ten_days',
    'fifteen_days',
    'thirty_days',
    'thirty_days_end_of_month',
    'forty_five_days',
    'forty_five_days_end_of_month',
    'sixty_days',
    'sixty_days_end_of_month',
    'ninety_days',
    'ninety_days_end_of_month',
    'one_hundred_and_twenty_days',
    'other'
]);

export const zPaymentMethod = z.enum([
    'transfer',
    'direct_debit',
    'credit_card',
    'cheque',
    'universal_employment_service_cheque',
    'cash',
    'paypal',
    'stripe',
    'other'
]);

/**
 * The provider of the payment account
 */
export const zPaymentProvider = z.enum(['stripe_connect']).describe('The provider of the payment account');

export const zPaymentRequestPayloadDto = z.object({
    advanceAlreadyPaid: z.number().describe('Amount in cents of the advance already paid. This amount must not exceed 50% of the total including or excluding tax of the invoice.'),
    dateDebutEmploi: z.number().describe('Date of the beginning of the employment period.'),
    dateFinEmploi: z.number().describe('Date of the end of the employment period.')
});

export const zPaymentRequestStatusUrssafTp = z.union([
    z.literal(0),
    z.literal('10'),
    z.literal('20'),
    z.literal('30'),
    z.literal('40'),
    z.literal('50'),
    z.literal('70'),
    z.literal('60'),
    z.literal('110'),
    z.literal('111'),
    z.literal('120'),
    z.literal('112'),
    z.literal('ERR_PARTICULIER_INCONNU'),
    z.literal('ERR_CMPT_BLOQUE'),
    z.literal('ERR_FACTURE_DOUBLON'),
    z.literal('ERR_NBRE_PREST_MAX'),
    z.literal('ERR_DATE_FUTUR'),
    z.literal('ERR_DATE_PAIEMENT_AVANT_EXP'),
    z.literal('ERR_PERIODE_EMPLOI_MOIS_NON_UNIQUE'),
    z.literal('ERR_DATE_FIN_AVANT_DATE_DEB'),
    z.literal('ERR_MONTANT_ACOMPTE'),
    z.literal('ERR_TOTAL_PRESTATIONS'),
    z.literal('ERR_CODE_NATURE'),
    z.literal('ERR_CODE_ACTIVITE'),
    z.literal('ERR_CODE_ACTIVITE_NATURE'),
    z.literal('ERR_MNT_PREST_HT_TVA'),
    z.literal('ERR_MNT_PREST_TTC'),
    z.literal('ERR_VALEUR_NEGATIVE'),
    z.literal('ERR_PRESTATAIRE_EMETTEUR_INCONNU'),
    z.literal('ERR_LIEN_PARTICULIER_PRESTATAIRE'),
    z.literal('ERR_PRESTATAIRE_FACTURATION_INCONNU'),
    z.literal('ERR_CRITERE_RECHERCHE_VIDE'),
    z.literal('ERR_DGFIP_R2P_INCONNU'),
    z.literal('ERR_DATE_NAISSANCE_FUTUR'),
    z.literal('ERR_LIEU_NAISSANCE_DEPT'),
    z.literal('ERR_LIEU_NAISSANCE_COMN'),
    z.literal('ERR_LIEU_NAISSANCE_PAYS'),
    z.literal('ERR_DGFIP_IMPOTPART_INCONNU'),
    z.literal('ERR_CONTACT'),
    z.literal('ERR_CONTACT_ADRESSE_TYPE_VOIE'),
    z.literal('ERR_CONTACT_ADRESSE_LETTRE_VOIE'),
    z.literal('ERR_CONTACT_ADRESSE_TYPEVOIE'),
    z.literal('ERR_CONTACT_ADRESSE_LIBELLEVOIE'),
    z.literal('ERR_CONTACT_ADRESSE_INFORMATION_SUPPLEMENTAIRE'),
    z.literal('ERR_CONTACT_ADRESSE_COMMUNE'),
    z.literal('ERR_COORDONNEES_BANCAIRES'),
    z.literal('ERR_FORMAT_VALEUR'),
    z.literal('ERR_NBRE_MAX_RESULTAT'),
    z.literal('ERR_RECHERCHE_VIDE'),
    z.literal('ERR_ECV_PARTICULIERS_EXISTENT'),
    z.literal('ERREUR_REFERENCE_PARTICULIER_EXISTANTE_TYPE'),
    z.literal('ERR_LIEU_NAISSANCE_OBLIGATOIRE'),
    z.literal('ERREUR_LIEU_NAISSANCE_INVALIDE'),
    z.literal('ERR_RECHERCHE_PARTICULIER'),
    z.literal('ERR_FORMAT_NUMINTERVENANT'),
    z.literal('ERR_NUMINTERVENANT_MANQUANT'),
    z.literal('ERR_NUMINTERVENANT_BLOQUE'),
    z.literal('ERR_MANDAT_ECHU'),
    z.literal('ERREUR_VALIDATION'),
    z.literal('ERREUR_TECHNIQUE'),
    z.literal('ERREUR_INCONNUE')
]);

export const zPaymentRequestDto = z.object({
    idDemandePaiement: z.string().optional(),
    dateDebutEmploi: z.number(),
    dateFinEmploi: z.number(),
    dateVirement: z.number().optional(),
    advanceAlreadyPayed: z.number().optional(),
    mntVirement: z.number().optional(),
    statut: zPaymentRequestStatusUrssafTp.optional()
});

export const zPersonalServiceActivity = z.enum([
    'GARDE_ENFANT_HANDICAPE',
    'ACCOMPAGNEMENT_ENFANT_HANDICAPE',
    'AIDE_HUMAINE',
    'CONDUITE_VEHICULE_PERSONNEL',
    'AIDE_AU_DEPLACEMENT',
    'ENTRETIEN_DE_LA_MAISON',
    'JARDINAGE',
    'BRICOLAGE',
    'GARDE_ENFANT_PLUS_DE_6_ANS',
    'SOUTIEN_SCOLAIRE_COURS_A_DOMICILE',
    'SOIN_ESTHETIQUE_A_DOMICILE',
    'PREPARATION_REPAS_A_DOMICILE',
    'LIVRAISON_REPAS_A_DOMICILE',
    'COLLECTE_ET_LIVRAISON_DE_LINGE_REPASSE',
    'LIVRAISON_COURSES_A_DOMICILE',
    'ASSISTANCE_INFORMATIQUE',
    'SOINS_ET_PROMENADES_ANIMAUX_DE_COMPAGNIE_POUR_PERSONNES_DEPENDANTES',
    'MAINTENANCE_ENTRETIEN_ET_VIGILANCE_DE_LA_RESIDENCE_PRINCIPALE',
    'ASSISTANCE_ADMINISTRATIVE',
    'ACCOMPAGNEMENT_ENFANT_PLUS_DE_6_ANS',
    'TELEASSISTANCE',
    'INTERPRETE_LANGUE_DES_SIGNES',
    'CONDUITE_VEHICULE_PERSONNEL_EN_CAS_INVALIDITE_TEMPORAIRE',
    'ACCOMPAGNEMENT_DEPLACEMENTS_EN_DEHORS_DU_DOMICILE',
    'ASSISTANCE_PERSONNES_TEMPORAIREMENT_DEPENDANTES_A_DOMICILE',
    'COORDINATION_ET_GESTION',
    'DIVERS_NON_ELIGIBLE'
]);

export const zProductType = z.enum([
    'sale_of_goods',
    'service_delivery',
    'commercial_or_craft_services',
    'sale_of_manufactured_goods',
    'disbursement'
]);

export const zProductUnit = z.enum([
    'unit',
    'gram',
    'hour',
    'day',
    'week',
    'fixed_rate',
    'year',
    'character',
    'line',
    'license',
    'article',
    'month',
    'kilogram',
    'kilometer',
    'liter',
    'batch',
    'meter',
    'square_meter',
    'cubic_meter',
    'linear_meter',
    'person',
    'ton',
    'word',
    'page',
    'leaflet',
    'paragraph',
    'minute',
    'overnight_stay'
]);

export const zMigrateSapProductLineDto = z.object({
    lineId: z.string().describe('ID of the billing line to update'),
    ignore: z.boolean().describe('If true, the line will not be included as a personal service product').optional(),
    quantityUnit: zProductUnit.optional(),
    personalServiceActivity: zPersonalServiceActivity.optional()
});

export const zMigrateSapProductsDto = z.object({
    lines: z.array(zMigrateSapProductLineDto).describe('Lines to migrate for SAP compliance')
});

export const zPushNotificationPreferencesDto = z.object({
    urssafReminder: z.boolean().describe('Urssaf reminders')
});

export const zNotificationPreferencesDto = z.object({
    push: zPushNotificationPreferencesDto
});

export const zReadAdvanceItemLineDto = z.object({
    value: z.number().describe('The value of the advance (amount or percentage)'),
    mode: zAdvanceMode,
    paymentCondition: zPaymentCondition.optional(),
    customPaymentCondition: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zReadAdvanceItemLineTotalsDto = z.object({
    totalAmountWithoutTax: z.number().describe('Total amount of all advances'),
    totalAmountWithTax: z.number().describe('Total amount of all advances after discount'),
    remainingTotalAmountWithoutTax: z.number().describe('Remaining total amount without tax'),
    remainingTotalAmountWithTax: z.number().describe('Remaining total amount with tax')
});

export const zReadBankInformationDto = z.object({
    bic: z.string(),
    iban: z.string(),
    holder: z.string()
});

export const zReadBillingCustomerDto: z.AnyZodObject = z.object({
    id: z.string().describe('Unique identifier of the customer'),
    legacyId: z.string().describe('Legacy identifier of the customer'),
    currency: zCurrencyCode.optional(),
    firstname: z.string().describe('First name of the customer').optional(),
    lastname: z.string().describe('Last name of the customer').optional(),
    phoneNumber: z.string().describe('Phone number of the customer').optional(),
    emails: z.array(z.string()).describe('Email addresses of the customer').optional(),
    billingAddress: zAddressDto,
    deliveryAddress: zAddressDto.optional(),
    deliveryAddressIsSame: z.boolean().describe('Tell if delivery and billing address are deep equal or not'),
    language: z.string().describe('Preferred language of the customer').optional(),
    name: z.string().describe('Full name of the customer').optional(),
    commercialName: z.string().describe('Commercial name of the customer').optional(),
    siren: z.string().describe('SIREN number of the customer').optional(),
    siret: z.string().describe('SIRET number of the customer').optional(),
    nafCode: z.string().describe('NAF code of the customer').optional(),
    vatNumber: z.string().describe('VAT number of the customer').optional(),
    token: z.string().describe('Token associated with the customer'),
    parent: z.lazy(() => zReadBillingCustomerDto).optional(),
    contactId: z.string().describe('Contact identifier associated with the customer').optional(),
    organizationId: z.string().describe('Organization identifier associated with the customer').optional(),
    isDefault: z.boolean().describe('Indicates if this is the default customer').optional(),
    test: z.boolean().describe('Indicates if this is a test customer')
});

export const zReadBillingEmailDto = z.object({
    subject: z.string().describe('The subject of the email with rendered variables'),
    content: z.string().describe('The content of the email with rendered variables')
});

export const zReadBillingEmitterDto = z.object({
    name: z.string().optional(),
    fullName: z.string().optional(),
    email: z.string().optional(),
    phone: z.string().optional(),
    commercialName: z.string().optional(),
    siret: z.string().optional(),
    vatNumber: z.string().optional(),
    rcsNumber: z.string().optional(),
    legalStatus: zLegalStatus.optional(),
    sapAgreementNumber: z.string().optional(),
    hasVat: z.boolean().optional()
});

export const zReadCategoryDto = z.object({
    id: z.string().describe('The category ID'),
    companyId: z.string().describe('The company ID'),
    name: z.string().describe('The name of the category'),
    rank: z.string().describe('The rank for ordering'),
    showDueDate: z.boolean().describe('Show due date on opportunities'),
    showAmount: z.boolean().describe('Show amount on opportunities'),
    showCustomer: z.boolean().describe('Show customer on opportunities'),
    color: z.string().describe('The color of the category (hex)'),
    isLost: z.boolean().describe('Whether this is a lost category'),
    isDone: z.boolean().describe('Whether this is a done category'),
    count: z.number().describe('Number of opportunities in this category')
});

export const zReadContactDto = z.object({
    id: z.string().describe('Contact ID'),
    emails: z.array(z.string()).describe('Contact email addresses').optional(),
    organization: zOrganizationDto.optional(),
    defaultContact: z.boolean().describe('Whether this is the default contact').optional(),
    createdAt: z.number().describe('Contact creation timestamp'),
    archivedAt: z.number().describe('Contact archival timestamp').optional(),
    hasBillings: z.boolean().describe('Whether the contact has billings'),
    test: z.boolean().describe('Whether this is a test contact'),
    phone: z.string().describe('Contact phone number').optional(),
    firstname: z.string().describe('Contact first name'),
    lastname: z.string().describe('Contact last name'),
    billingAddress: zClientAddressDto.optional(),
    deliveryAddress: zClientAddressDto.optional(),
    jobTitle: z.string().describe('Contact job title').optional(),
    bankInformations: zBankInformationsDto.optional(),
    hasTiersPrestation: z.boolean().describe('Whether the contact has third-party services'),
    notes: z.string().describe('Additional notes about the contact').optional(),
    language: zBillingLocale.optional(),
    currency: zCurrencyCode.optional(),
    paymentMethods: zPaymentMethod.optional()
});

export const zReadCurrencyDto = z.object({
    currencyCode: zCurrencyCode,
    currencyDate: z.number(),
    currencyRate: z.number(),
    origin: zCurrencyOrigin
});

export const zReadCustomerAddressDto = z.object({
    line1: z.string().describe('First line of address'),
    line2: z.string().describe('Second line of address').optional(),
    city: z.string().describe('City name'),
    zipCode: z.string().describe('Postal/ZIP code'),
    country: zCountryCode
});

export const zReadEstimateAdvanceLinesDto = z.object({
    advances: z.array(zReadAdvanceItemLineDto).describe('Array of advance items'),
    totals: zReadAdvanceItemLineTotalsDto,
    convertedTotals: zReadAdvanceItemLineTotalsDto
});

export const zReadFileDto = z.object({
    id: z.string(),
    name: z.string(),
    extension: z.string(),
    mimeType: z.string(),
    url: z.string(),
    relativeUrl: z.string(),
    isCertified: z.boolean().optional(),
    isCertifiable: z.boolean().optional()
});

export const zReadOrganizationDto = z.object({
    language: zBillingLocale.optional(),
    currency: zCurrencyCode.optional(),
    paymentMethods: z.array(z.string()).describe('The client\'s preferred payment methods').optional(),
    id: z.string(),
    name: z.string(),
    commercialName: z.string(),
    emails: z.array(z.string()),
    siret: z.string(),
    vatNumber: z.string(),
    countContacts: z.number(),
    billingAddress: zClientAddressDto,
    deliveryAddress: zClientAddressDto,
    bankInformations: zBankInformationsDto,
    notes: z.string(),
    createdAt: z.number().describe('Contact creation timestamp'),
    archivedAt: z.number().describe('Contact archival timestamp'),
    hasBillings: z.boolean(),
    test: z.boolean()
});

export const zReadOrganizationsDto = z.object({
    countWithoutFilters: z.number(),
    totalDocs: z.number(),
    limit: z.number(),
    totalPages: z.number(),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    nextPage: z.number(),
    page: z.number(),
    prevPage: z.number(),
    docs: z.array(zReadOrganizationDto)
});

export const zReadPaymentAccountDto = z.object({
    id: z.string().describe('The ID of the payment account'),
    externalId: z.string().describe('The external ID of the payment account'),
    provider: zPaymentProvider,
    status: zPaymentAccountStatus,
    reason: z.union([
        zPaymentAccountIssueReason,
        z.null()
    ])
});

export const zReadTiersPrestationDto = z.object({
    idClient: z.string().describe('Client identifier'),
    registeredAt: z.number().describe('Registration timestamp'),
    status: zClientState
});

export const zReadCustomerDto: z.AnyZodObject = z.object({
    id: z.string().describe('Unique identifier'),
    legacyId: z.string().describe('Legacy system identifier'),
    paymentMethods: z.array(z.string()).describe('List of payment method identifiers').optional(),
    currency: zCurrencyCode.optional(),
    firstname: z.string().describe('Customer first name').optional(),
    lastname: z.string().describe('Customer last name').optional(),
    phoneNumber: z.string().describe('Contact phone number').optional(),
    emails: z.array(z.string()).describe('List of email addresses').optional(),
    billingAddress: zReadCustomerAddressDto,
    deliveryAddress: zReadCustomerAddressDto.optional(),
    deliveryAddressIsSame: z.boolean().describe('Tell if delivery and billing address are deep equal or not'),
    language: z.string().describe('Preferred language code').optional(),
    name: z.string().describe('Business name').optional(),
    commercialName: z.string().describe('Commercial/trading name').optional(),
    siren: z.string().describe('SIREN number').optional(),
    siret: z.string().describe('SIRET number').optional(),
    nafCode: z.string().describe('NAF/APE code').optional(),
    vatNumber: z.string().describe('VAT identification number').optional(),
    token: z.string().describe('Customer token'),
    tiersPrestationIsActivated: z.boolean().describe('Tiers prestation activation status').optional(),
    tiersPrestation: zReadTiersPrestationDto.optional(),
    parent: z.lazy(() => zReadCustomerDto).optional(),
    contactId: z.string().describe('Associated contact ID').optional(),
    organizationId: z.string().describe('Associated organization ID').optional(),
    isDefault: z.boolean().describe('Default status flag').optional(),
    test: z.boolean().describe('Test account flag'),
    archivedAt: z.number().describe('Archived at').optional()
});

export const zReadOpportunityDto = z.object({
    id: z.string().describe('The opportunity ID'),
    createdAt: z.number().describe('The creation date as Unix timestamp'),
    name: z.string().describe('The name of the opportunity'),
    description: z.string().describe('The description of the opportunity').optional(),
    dueDate: z.number().describe('The due date as Unix timestamp').optional(),
    amount: z.number().describe('The amount in cents'),
    rank: z.string().describe('The rank for ordering'),
    customerId: z.string().describe('The legacy customer ID'),
    categoryId: z.string().describe('The category ID'),
    category: zReadCategoryDto,
    customer: zReadCustomerDto
});

/**
 * The frequency at which reminders should be sent
 */
export const zReminderFrequency = z.enum(['on_due_date', 'every_week']).describe('The frequency at which reminders should be sent');

export const zBillingReminderDto = z.object({
    inCopy: z.boolean().describe('Indicates if the sender should be in copy of the reminder'),
    frequency: zReminderFrequency,
    numberOfRemindersToSend: z.number().describe('The number of reminders to be sent'),
    active: z.boolean().describe('Indicates if the reminder is active'),
    recipients: z.array(z.string()).describe('Array of email addresses to receive the reminder').optional()
});

export const zReminderDto = z.object({
    inCopy: z.boolean(),
    frequency: zReminderFrequency,
    numberOfRemindersToSend: z.number(),
    active: z.boolean(),
    recipients: z.array(z.string())
});

export const zRentabilityPreferencesDto = z.object({
    defaultProductMargin: z.number().describe('Marge par défaut pour les produits (en pourcentage)'),
    defaultOverheadCosts: z.number().describe('Coûts généraux par défaut (en pourcentage)')
});

export const zPreferencesDto = z.object({
    rentability: zRentabilityPreferencesDto,
    notification: zNotificationPreferencesDto
});

export const zRetrieveCustomerPortalPaymentsDto = z.object({
    customer: zCustomerPortalCustomerDto,
    billings: z.array(zCustomerPortalBillingDto),
    company: zCustomerPortalCompanyDto,
    email: z.string(),
    phone: z.string().optional()
});

export const zSendBillingByEmailDto = z.object({
    emails: z.array(z.string()).max(10).describe('List of email addresses to send the billing document to'),
    subject: z.string().max(255).describe('Email subject'),
    content: z.string().describe('Email content (HTML supported)'),
    inCopy: z.boolean().describe('Whether to send a copy to the sender').optional().default(false)
});

export const zSendTestEmailSignatureDto = z.object({
    content: z.string().optional()
});

export const zSetDefaultContactDto = z.object({
    defaultContactId: z.string()
});

export const zTiersPrestationDto = z.object({
    state: zClientState
});

export const zReadContactListItemDto = z.object({
    archivedAt: z.number().describe('Contact archival timestamp').optional(),
    createdAt: z.number().describe('Contact creation timestamp'),
    test: z.boolean().describe('Whether this is a test contact'),
    defaultContact: z.boolean().describe('Whether this is the default contact').optional(),
    emails: z.array(z.string()).describe('Contact email addresses').optional(),
    hasBillings: z.boolean().describe('Whether the contact has billings'),
    id: z.string().describe('Contact ID'),
    fullname: z.string().describe('Contact full name'),
    organization: zOrganizationDto.optional(),
    tiersPrestation: zTiersPrestationDto.optional()
});

export const zReadContactsDto = z.object({
    countWithoutFilters: z.number(),
    totalDocs: z.number(),
    limit: z.number(),
    totalPages: z.number(),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    nextPage: z.number(),
    page: z.number(),
    prevPage: z.number(),
    docs: z.array(zReadContactListItemDto)
});

export const zUpdateBillingBankInformationDto = z.object({
    bankInformation: z.union([
        zBankInformationDto,
        z.null()
    ])
});

export const zUpdateBillingCurrencyDto = z.object({
    currency: zCurrencyCode,
    currencyRate: z.number().describe('The conversion rate from the billing currency to the new currency').optional()
});

export const zUpdateBillingDisplaySettingsDto = z.object({
    displayFullName: z.boolean().describe('Afficher le nom complet'),
    displayEmail: z.boolean().describe('Afficher l\'email'),
    displayPhoneNumber: z.boolean().describe('Afficher le numéro de téléphone'),
    displaySAPAgreement: z.boolean().describe('Afficher l\'accord SAP'),
    displayLegalStatus: z.boolean().describe('Afficher le statut légal'),
    displayRequiredMentionsProduct: z.boolean().describe('Afficher les mentions obligatoires du produit'),
    displayMemberOfAnApprovedAssociation: z.boolean().describe('Afficher "Membre d\'une association agréée"'),
    displayAbbyLogo: z.boolean().describe('Afficher le logo Abby'),
    displayTitle: z.boolean().describe('Afficher le titre de la facture'),
    displayGoodForApproval: z.boolean().describe('Afficher la mention bon pour accord').optional(),
    displayEstimateNumber: z.boolean().describe('Afficher le numéro du devis ou du bon de commande').optional()
});

export const zUpdateBillingLocaleDto = z.object({
    locale: zBillingLocale
});

export const zUpdateContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.string().optional(),
    jobTitle: z.string().optional(),
    emails: z.array(z.string()).optional(),
    billingAddress: zClientAddressDto.optional(),
    deliveryAddress: zClientAddressDto.optional(),
    bankInformations: zBankInformationsDto.optional(),
    preferences: zClientPreferencesDto.optional()
});

export const zUpdateDeliveryAddressDto = z.object({
    line1: z.string().describe('First line of address'),
    line2: z.string().describe('Second line of address').optional(),
    city: z.string().describe('City name'),
    zipCode: z.string().describe('Postal/ZIP code'),
    country: zCountryCode
});

export const zUpdateBillingDeliveryAddressDto = z.object({
    deliveryAddress: z.union([
        zUpdateDeliveryAddressDto,
        z.null()
    ]),
    displayDeliveryAddress: z.boolean().describe('Display delivery address')
});

export const zUpdateEstimateAdvanceLinesDto = z.object({
    advances: z.array(zAdvanceItemDto).describe('Array of advance items')
});

export const zUpdateEstimateTimelineDto = z.object({
    emittedAt: z.number().describe('The timestamp when the invoice was emitted'),
    paymentDelay: zPaymentDelay,
    customDueDate: z.number().describe('Custom due date for the invoice when payment delay is OTHER').optional(),
    deliveryDate: z.union([
        z.number(),
        z.null()
    ]).optional(),
    expiredAt: z.number().describe('The timestamp when the estimate expired')
});

export const zUpdateInvoiceBankInformationDto = z.object({
    bankInformation: z.union([
        zBankInformationDto,
        z.null()
    ])
});

export const zUpdateInvoiceDeliveryAddressDto = z.object({
    deliveryAddress: z.union([
        zUpdateDeliveryAddressDto,
        z.null()
    ]),
    displayDeliveryAddress: z.boolean().describe('Display delivery address')
});

export const zUpdateInvoiceFrequencyDto = z.object({
    from: z.string(),
    to: z.string(),
    frequency: z.number(),
    interval: zFrequencyInterval,
    finalizeInvoice: z.boolean(),
    sendByMail: z.boolean(),
    inCopy: z.boolean()
});

export const zUpdateInvoicePaymentRequestDto = z.object({
    paymentRequest: z.union([
        zPaymentRequestPayloadDto,
        z.null()
    ])
});

export const zUpdateInvoiceTimelineDto = z.object({
    emittedAt: z.number().describe('The timestamp when the invoice was emitted'),
    paymentDelay: zPaymentDelay,
    customDueDate: z.number().describe('Custom due date for the invoice when payment delay is OTHER').optional(),
    deliveryDate: z.union([
        z.number(),
        z.null()
    ]).optional()
});

export const zUpdateOpportunityDto = z.object({
    name: z.string().describe('The name of the opportunity').optional(),
    description: z.string().describe('The description of the opportunity (null to remove)').optional(),
    dueDate: z.string().describe('The due date as ISO date string YYYY-MM-DD (null to remove)').optional(),
    amount: z.number().describe('The amount in cents').optional(),
    customerId: z.string().describe('The legacy customer ID').optional(),
    categoryId: z.string().describe('The category ID').optional(),
    afterRank: z.string().describe('The rank to insert after').optional()
});

export const zUpdateOrganizationContactDto = z.object({
    firstname: z.string(),
    lastname: z.string(),
    phone: z.string().optional(),
    jobTitle: z.string().optional(),
    emails: z.array(z.string()).optional(),
    notes: z.string().optional(),
    defaultContact: z.boolean().optional()
});

export const zUpdateOrganizationDto = z.object({
    name: z.string(),
    commercialName: z.string().optional(),
    emails: z.array(z.string()).optional(),
    siret: z.string().optional(),
    vatNumber: z.string().optional(),
    billingAddress: zClientAddressDto.optional(),
    deliveryAddress: zClientAddressDto.optional(),
    bankInformations: zBankInformationsDto.optional(),
    notes: z.string().optional(),
    preferences: zClientPreferencesDto.optional()
});

export const zUpdateTitleDto = z.object({
    title: z.union([
        z.string(),
        z.null()
    ])
});

export const zUserDto = z.object({
    id: z.string().describe('Identifiant unique de l\'utilisateur'),
    email: z.string().describe('Adresse email de l\'utilisateur'),
    firstname: z.string().describe('Prénom de l\'utilisateur'),
    lastname: z.string().describe('Nom de l\'utilisateur'),
    fullname: z.string().describe('Nom complet de l\'utilisateur'),
    firebaseToken: z.string().describe('Token Firebase de l\'utilisateur'),
    address: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zReadMeDto = z.object({
    company: zCompanyDto,
    preferences: zPreferencesDto,
    user: zUserDto
});

export const zVatCode = z.enum([
    'FR_210',
    'FR_550',
    'FR_850',
    'FR_1000',
    'FR_2000',
    'FR_00HT',
    'FR_00UE',
    'FR_0HUE'
]);

export const zReadBillingDetailsLineDto = z.object({
    generatedId: z.string().optional(),
    id: z.string().optional(),
    unitPrice: z.number(),
    productId: z.string().optional(),
    quantity: z.number().optional(),
    quantityUnit: zProductUnit.optional(),
    designation: z.string(),
    reference: z.string().optional(),
    description: z.string().optional(),
    isDeliveryOfGoods: z.boolean(),
    type: zProductType.optional(),
    vatCode: zVatCode.optional(),
    personalServiceActivity: zPersonalServiceActivity.optional(),
    priceWithoutTaxBeforeDiscount: z.number(),
    discountAmount: z.number(),
    discount: zDiscountLineDto,
    priceWithoutTaxAfterDiscount: z.number(),
    vatAmount: z.number(),
    priceTotalTax: z.number(),
    convertedAmounts: zConvertedAmountsLineDto.optional(),
    isTaxIncluded: z.boolean().describe('Indicates whether the unit price includes tax (TTC) or excludes tax (HT)').optional()
});

export const zUpdateLineDto = z.object({
    generatedId: z.string().describe('Warning: Client-side generated line id. This field will be deprecated and will be removed in the future.').optional(),
    productId: z.string().describe('Unique identifier of the product, if applicable').optional(),
    unitPrice: z.number().describe('Price per unit in cents (e.g., 1500 for 15.00 euros)'),
    quantity: z.number().describe('Quantity of the product or service'),
    quantityUnit: z.union([
        zProductUnit,
        z.null()
    ]),
    designation: z.string().describe('Name or short description of the product or service'),
    reference: z.string().describe('Product reference or SKU, if applicable').optional(),
    description: z.string().describe('Detailed description of the product or service').optional(),
    type: z.union([
        zProductType,
        z.null()
    ]),
    vatCode: zVatCode,
    personalServiceActivity: zPersonalServiceActivity.optional(),
    discount: zDiscountDto.optional(),
    isDeliveryOfGoods: z.boolean().describe('Mark a product line as delivery of goods to display it on document').optional(),
    isTaxIncluded: z.boolean().describe('Indicates whether the unit price includes tax (TTC) or excludes tax (HT)').optional().default(false)
});

export const zUpdateBillingLinesDto = z.object({
    lines: z.array(zUpdateLineDto).describe('Array of billing lines, each representing a product or service'),
    discount: zDiscountDto.optional()
});

export const zVatDetailDto = z.object({
    vatCode: zVatCode,
    amount: z.number(),
    vatRate: z.number()
});

export const zConvertedAmountsDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingAmountToBill: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.number().optional(),
    billedAmountWithoutTax: z.number(),
    billedAmountWithTax: z.number(),
    remainingAmountWithoutTaxWithoutDisbursement: z.number(),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number()
});

export const zEstimateTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingAmountToBill: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.number().optional(),
    convertedAmounts: zConvertedAmountsDto.optional(),
    billedAmountWithoutTax: z.number(),
    billedAmountWithTax: z.number(),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number(),
    remainingAmountWithoutTaxWithoutDisbursement: z.number()
});

export const zReadInvoiceTotalWithoutConvertedAmountsDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    discountAmount: z.number().optional(),
    vatDetails: z.array(zVatDetailDto),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number()
});

export const zReadInvoiceTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    discountAmount: z.number().optional(),
    vatDetails: z.array(zVatDetailDto),
    amountWithoutTaxBeforeDiscountWithoutDisbursement: z.number(),
    convertedAmounts: zReadInvoiceTotalWithoutConvertedAmountsDto.optional()
});

export const zTotalDto = z.object({
    amountWithoutTaxBeforeDiscount: z.number(),
    amountWithoutTaxAfterDiscount: z.number(),
    amountWithTaxAfterDiscount: z.number(),
    remainingAmountWithoutTax: z.number(),
    remainingAmountWithTax: z.number(),
    remainingReconciliateAmount: z.number(),
    vatDetails: z.array(zVatDetailDto),
    discountAmount: z.number().optional(),
    convertedAmounts: zConvertedAmountsDto.optional()
});

export const zVatMention = z.enum([
    'not_subject',
    'second_hand_good',
    'art_object',
    'collection_antique',
    'travel_agency',
    'vat_not_applicable',
    'vat_not_applicable_2',
    'vat_exemption',
    'vat_exemption_eu_sale',
    'vat_exemption_eu_service',
    'vat_construction',
    'vat_psychologist',
    'vat_psychologist_2',
    'vat_reverse_charge',
    'vat_reverse_charge_2',
    'vat_reverse_charge_3',
    'vat_reverse_charge_4',
    'vat_reduced_rate',
    'vat_reduced_rate_2',
    'vat_article_261c_cgi',
    'vat_exemption_294_cgi'
]);

export const zBillingLegalsDto = z.object({
    headerNote: z.string().optional(),
    footerNote: z.string().optional(),
    generalTermsAndConditionsOfSale: z.string().optional(),
    mentionMediator: z.string().optional(),
    vatMention: zVatMention,
    paymentMethods: z.array(zPaymentMethod),
    otherPaymentMethod: z.string().describe('Other payment method').optional()
});

export const zUpdateAdvanceGeneralInformationsDto = z.object({
    headerNote: z.string().describe('Custom note to be displayed in the header of the billing').optional(),
    footerNote: z.string().describe('Custom note to be displayed in the footer of the billing').optional(),
    generalTermsAndConditionsOfSale: z.string().describe('General terms and conditions of sale to be included in the billing').optional(),
    mentionMediator: z.string().describe('Mention mediateur to be included in the billing').optional(),
    paymentMethods: z.array(z.string()).describe('Array of accepted payment methods for the billing').optional(),
    otherPaymentMethod: z.string().describe('Other payment method').optional(),
    vatMention: zVatMention.optional(),
    latePenalty: z.union([
        zBillingLatePenaltyDto,
        z.null()
    ]).optional(),
    lumpSumCompensation: z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ]).optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    isOnlinePaymentActivated: z.boolean().describe('Indicates if online payment is activated for this invoice').optional(),
    reminder: zBillingReminderDto.optional()
});

export const zUpdateAssetGeneralInformationsDto = z.object({
    headerNote: z.string().describe('Custom note to be displayed in the header of the billing').optional(),
    footerNote: z.string().describe('Custom note to be displayed in the footer of the billing').optional(),
    generalTermsAndConditionsOfSale: z.string().describe('General terms and conditions of sale to be included in the billing').optional(),
    mentionMediator: z.string().describe('Mention mediateur to be included in the billing').optional(),
    paymentMethods: z.array(z.string()).describe('Array of accepted payment methods for the billing').optional(),
    otherPaymentMethod: z.string().describe('Other payment method').optional(),
    vatMention: zVatMention.optional(),
    latePenalty: z.union([
        zBillingLatePenaltyDto,
        z.null()
    ]).optional(),
    lumpSumCompensation: z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ]).optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional()
});

export const zUpdateEstimateGeneralInformationsDto = z.object({
    headerNote: z.string().describe('Custom note to be displayed in the header of the billing').optional(),
    footerNote: z.string().describe('Custom note to be displayed in the footer of the billing').optional(),
    generalTermsAndConditionsOfSale: z.string().describe('General terms and conditions of sale to be included in the billing').optional(),
    mentionMediator: z.string().describe('Mention mediateur to be included in the billing').optional(),
    paymentMethods: z.array(z.string()).describe('Array of accepted payment methods for the billing').optional(),
    otherPaymentMethod: z.string().describe('Other payment method').optional(),
    vatMention: zVatMention.optional(),
    latePenalty: z.union([
        zBillingLatePenaltyDto,
        z.null()
    ]).optional(),
    lumpSumCompensation: z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ]).optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional()
});

export const zUpdateInvoiceGeneralInformationsDto = z.object({
    headerNote: z.string().describe('Custom note to be displayed in the header of the billing').optional(),
    footerNote: z.string().describe('Custom note to be displayed in the footer of the billing').optional(),
    generalTermsAndConditionsOfSale: z.string().describe('General terms and conditions of sale to be included in the billing').optional(),
    mentionMediator: z.string().describe('Mention mediateur to be included in the billing').optional(),
    paymentMethods: z.array(z.string()).describe('Array of accepted payment methods for the billing').optional(),
    otherPaymentMethod: z.string().describe('Other payment method').optional(),
    vatMention: zVatMention.optional(),
    latePenalty: z.union([
        zBillingLatePenaltyDto,
        z.null()
    ]).optional(),
    lumpSumCompensation: z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ]).optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    isOnlinePaymentActivated: z.boolean().describe('Indicates if online payment is activated for this invoice').optional(),
    reminder: zBillingReminderDto.optional()
});

export const zReadAdvanceDto: z.AnyZodObject = z.object({
    id: z.string(),
    number: z.string().optional(),
    title: z.string().describe('Title of the billing document').optional(),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.number().optional(),
    opportunity: zOpportunityDto.optional(),
    locked: z.boolean().optional(),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.number().optional(),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: zReadBankInformationDto.optional(),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.number().optional(),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.number().optional(),
    lastSendByEmailAt: z.number().optional(),
    paymentDelay: zPaymentDelay,
    dueAt: z.number().optional(),
    paidAt: z.number().optional(),
    lastReminderSentAt: z.number().optional(),
    isReminderActivated: z.boolean(),
    designation: z.string(),
    isOnlinePaymentActivated: z.boolean(),
    description: z.string().optional(),
    total: zTotalDto,
    discount: zDiscountDto.optional(),
    displaySettings: zDisplaySettingsDto,
    parent: z.lazy(() => zReadEstimateDto).optional(),
    advanceMode: zAdvanceMode,
    advancePercentage: z.number(),
    advanceAmount: z.number(),
    reminder: zBillingReminderDto.optional(),
    latePenalty: zBillingLatePenaltyDto.optional(),
    lumpSumCompensation: zBillingLumpSumCompensationDto.optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    hasAssociatedTransaction: z.boolean().describe('Indicates if the customer has an associated transaction'),
    includeDisbursement: z.boolean().describe('Indicates if the advance includes disbursement'),
    canceledAt: z.number().optional()
});

export const zReadAssetDto: z.AnyZodObject = z.object({
    id: z.string(),
    number: z.string().optional(),
    title: z.string().describe('Title of the billing document').optional(),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.number().optional(),
    opportunity: zOpportunityDto.optional(),
    locked: z.boolean().optional(),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.number().optional(),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: zReadBankInformationDto.optional(),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.number().optional(),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.number().optional(),
    lastSendByEmailAt: z.number().optional(),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zReadInvoiceTotalDto,
    discount: zDiscountDto.optional(),
    parent: z.union([
        z.lazy(() => zReadInvoiceDto),
        zReadAdvanceDto
    ]).optional(),
    refundAt: z.number().optional(),
    latePenalty: z.union([
        zBillingLatePenaltyDto,
        z.null()
    ]).optional(),
    lumpSumCompensation: z.union([
        zBillingLumpSumCompensationDto,
        z.null()
    ]).optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    displaySettings: zDisplayBillingSettingsDto,
    dueAt: z.number().optional(),
    paymentDelay: zPaymentDelay,
    includeDiscountDisbursement: z.boolean()
});

export const zReadEstimateDto = z.object({
    id: z.string(),
    number: z.string().optional(),
    title: z.string().describe('Title of the billing document').optional(),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.number().optional(),
    opportunity: zOpportunityDto.optional(),
    locked: z.boolean().optional(),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.number().optional(),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: zReadBankInformationDto.optional(),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.number().optional(),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.number().optional(),
    lastSendByEmailAt: z.number().optional(),
    paymentDelay: zPaymentDelay,
    expiredAt: z.number(),
    refusedAt: z.number().optional(),
    signedAt: z.number().optional(),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zEstimateTotalDto,
    discount: zDiscountDto.optional(),
    latePenalty: zLatePenaltyDto.optional(),
    lumpSumCompensation: zLumpSumCompensationDto.optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    displaySettings: zDisplaySettingsDto,
    advances: z.array(zReadAdvanceDto),
    advanceEstimateLines: zReadEstimateAdvanceLinesDto,
    withElectronicSignature: z.boolean(),
    electronicSignature: zEstimateElectronicSignatureDto,
    dueAt: z.number().optional(),
    electronicSignatureRequirements: z.array(zElectronicSignatureRequirementDto),
    hasFinalInvoice: z.boolean(),
    includeDiscountDisbursement: z.boolean()
});

export const zReadInvoiceDto = z.object({
    id: z.string(),
    number: z.string().optional(),
    title: z.string().describe('Title of the billing document').optional(),
    type: zBillingType,
    state: zBillingState,
    customer: zReadBillingCustomerDto,
    locale: zBillingLocale,
    emittedAt: z.number(),
    archivedAt: z.number().optional(),
    opportunity: zOpportunityDto.optional(),
    locked: z.boolean().optional(),
    finalizable: z.boolean(),
    test: z.boolean(),
    isEditable: z.boolean(),
    currencyCode: zCurrencyCode,
    currency: zReadCurrencyDto,
    lastDownloadAt: z.number().optional(),
    attachments: z.array(zReadFileDto),
    finalizeRequirements: z.array(zFinalizeRequirementDto),
    emitter: zReadBillingEmitterDto,
    bankInformation: zReadBankInformationDto.optional(),
    billingLegals: zBillingLegalsDto,
    createdAt: z.number(),
    updatedAt: z.number(),
    deliveryDate: z.number().optional(),
    compatibilityVersion: zBillingCompatibilityVersion,
    isDeletable: z.boolean(),
    displayDeliveryAddress: z.boolean(),
    finalizedAt: z.number().optional(),
    lastSendByEmailAt: z.number().optional(),
    paymentDelay: zPaymentDelay,
    dueAt: z.number(),
    paidAt: z.number().optional(),
    lastReminderSentAt: z.number().optional(),
    isReminderActivated: z.boolean(),
    isOnlinePaymentActivated: z.boolean(),
    isFinalInvoice: z.boolean(),
    lines: z.array(zReadBillingDetailsLineDto),
    total: zReadInvoiceTotalDto,
    reminder: zReminderDto.optional(),
    discount: zDiscountDto.optional(),
    latePenalty: zLatePenaltyDto.optional(),
    lumpSumCompensation: zBillingLumpSumCompensationDto.optional(),
    discountAdvancePayment: z.union([
        zBillingDiscountAdvancePaymentDto,
        z.null()
    ]).optional(),
    displaySettings: zDisplayBillingSettingsDto,
    paymentRequest: z.union([
        zPaymentRequestDto,
        z.null()
    ]).optional(),
    parent: zReadEstimateDto.optional(),
    frequency: zFrequencyDto.optional(),
    hasAssociatedTransaction: z.boolean().describe('Indicates if the customer has an associated transaction'),
    includeDiscountDisbursement: z.boolean(),
    expiredAt: z.number().optional(),
    canceledAt: z.number().optional()
});

export const zBillingControllerDownloadPdfData = z.object({
    body: z.never().optional(),
    path: z.object({
        billingId: z.string()
    }),
    query: z.object({
        locale: zBillingLocale.optional()
    }).optional()
});

export const zBillingControllerDownloadPdfResponse = z.string();

export const zBillingControllerDeleteBillingDocumentData = z.object({
    body: z.never().optional(),
    path: z.object({
        documentId: z.string().describe('ID of the document to delete')
    }),
    query: z.never().optional()
});

/**
 * Document deleted successfully
 */
export const zBillingControllerDeleteBillingDocumentResponse = z.void().describe('Document deleted successfully');

export const zBillingControllerSendTestEmailSignatureData = z.object({
    body: zSendTestEmailSignatureDto,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Email sent successfully
 */
export const zBillingControllerSendTestEmailSignatureResponse = z.void().describe('Email sent successfully');

export const zBillingControllerRenderEmailData = z.object({
    body: z.never().optional(),
    path: z.object({
        billingId: z.string().describe('ID of the billing to render'),
        emailType: zBillingEmailType
    }),
    query: z.never().optional()
});

/**
 * Email rendu avec succès
 */
export const zBillingControllerRenderEmailResponse = zReadBillingEmailDto;

export const zBillingControllerSendEmailTestData = z.object({
    body: z.never().optional(),
    path: z.object({
        billingId: z.string().describe('ID of the billing to send the email test'),
        emailType: zBillingEmailType
    }),
    query: z.never().optional()
});

/**
 * Email sent successfully
 */
export const zBillingControllerSendEmailTestResponse = z.void().describe('Email sent successfully');

export const zBillingControllerSendByEmailData = z.object({
    body: zSendBillingByEmailDto,
    path: z.object({
        billingId: z.string().describe('ID of the billing document to send')
    }),
    query: z.never().optional()
});

/**
 * Email sent successfully
 */
export const zBillingControllerSendByEmailResponse = z.void().describe('Email sent successfully');

export const zBillingControllerRetrievePaymentAccountData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Payment account retrieved successfully
 */
export const zBillingControllerRetrievePaymentAccountResponse = zReadPaymentAccountDto;

export const zCustomerPortalControllerGetPaymentsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        id: z.string(),
        token: z.string()
    })
});

export const zCustomerPortalControllerGetPaymentsResponse = zRetrieveCustomerPortalPaymentsDto;

export const zContactControllerCreateContactData = z.object({
    body: zCreateContactDto,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * The contact has been successfully created.
 */
export const zContactControllerCreateContactResponse = zReadContactDto;

export const zContactControllerDeleteContactData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zContactControllerGetContactData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * The contact has been successfully retrieved.
 */
export const zContactControllerGetContactResponse = zReadContactDto;

export const zContactControllerUpdateContactData = z.object({
    body: zUpdateContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * The contact has been successfully updated.
 */
export const zContactControllerUpdateContactResponse = zReadContactDto;

export const zContactControllerGetContactByLegacyIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        legacyId: z.string()
    }),
    query: z.never().optional()
});

/**
 * The contact has been successfully retrieved.
 */
export const zContactControllerGetContactByLegacyIdResponse = zReadContactDto;

export const zContactsControllerRetrieveContactsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number().optional(),
        limit: z.number().optional(),
        search: z.string().optional(),
        orderBy: zContactOrderBy.optional(),
        orderDirection: zOrderDirection.optional(),
        archived: z.boolean().optional(),
        forCertificate: z.boolean().optional()
    }).optional()
});

/**
 * Successfully retrieved contacts
 */
export const zContactsControllerRetrieveContactsResponse = zReadContactsDto;

export const zOrganizationControllerCreateOrganizationData = z.object({
    body: zCreateOrganizationDto,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zOrganizationControllerCreateOrganizationResponse = zReadOrganizationDto;

export const zOrganizationControllerRetrieveOrganizationData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerRetrieveOrganizationResponse = zReadOrganizationDto;

export const zOrganizationControllerUpdateOrganizationData = z.object({
    body: zUpdateOrganizationDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerUpdateOrganizationResponse = zReadOrganizationDto;

export const zOrganizationControllerRetrieveOrganizationContactsData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerRetrieveOrganizationContactsResponse = z.array(zReadContactListItemDto);

export const zOrganizationControllerCreateOrganizationContactData = z.object({
    body: zCreateOrganizationContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerCreateOrganizationContactResponse = zReadContactDto;

export const zOrganizationControllerUpdateOrganizationContactData = z.object({
    body: zUpdateOrganizationContactDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerUpdateOrganizationContactResponse = zReadContactDto;

export const zOrganizationControllerDeleteOrganizationData = z.object({
    body: z.never().optional(),
    path: z.object({
        organizationId: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationControllerSetDefaultContactData = z.object({
    body: zSetDefaultContactDto,
    path: z.object({
        organizationId: z.string()
    }),
    query: z.never().optional()
});

export const zOrganizationsControllerRetrieveOrganizationsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        page: z.number(),
        limit: z.number(),
        search: z.string().optional(),
        orderBy: zOrganizationOrderBy.optional(),
        orderDirection: zOrderDirection.optional(),
        archived: z.boolean().optional()
    })
});

export const zOrganizationsControllerRetrieveOrganizationsResponse = zReadOrganizationsDto;

export const zOpportunityControllerRetrieveCategoriesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zOpportunityControllerRetrieveCategoriesResponse = z.array(zReadCategoryDto);

export const zOpportunityControllerDeleteOpportunityData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOpportunityControllerRetrieveOpportunityData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOpportunityControllerRetrieveOpportunityResponse = zReadOpportunityDto;

export const zOpportunityControllerUpdateOpportunityData = z.object({
    body: zUpdateOpportunityDto,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zOpportunityControllerUpdateOpportunityResponse = zReadOpportunityDto;

export const zOpportunityControllerCreateOpportunityData = z.object({
    body: zCreateOpportunityDto,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zOpportunityControllerCreateOpportunityResponse = zReadOpportunityDto;

export const zCompanyControllerGetMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Current company, user and preferences retrieved successfully
 */
export const zCompanyControllerGetMeResponse = zReadMeDto;

export const zEstimateControllerCreateEstimateByContactOrOrganizationIdData = z.object({
    body: zCreateEstimateByCustomerIdDto,
    path: z.object({
        customerId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Estimate created successfully
 */
export const zEstimateControllerCreateEstimateByContactOrOrganizationIdResponse = zReadEstimateDto;

export const zEstimateControllerUpdateTimelineData = z.object({
    body: zUpdateEstimateTimelineDto,
    path: z.object({
        estimateId: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Estimate timeline updated successfully
 */
export const zEstimateControllerUpdateTimelineResponse = zReadEstimateDto;

export const zEstimateControllerSignData = z.object({
    body: z.never().optional(),
    path: z.object({
        estimateId: z.string().describe('ID of the estimate or purchase order to sign')
    }),
    query: z.never().optional()
});

/**
 * Estimate or purchase order signed successfully
 */
export const zEstimateControllerSignResponse = zReadEstimateDto;

export const zEstimateControllerUnsignData = z.object({
    body: z.never().optional(),
    path: z.object({
        estimateId: z.string().describe('ID of the estimate or purchase order to unsign')
    }),
    query: z.never().optional()
});

/**
 * Estimate or purchase order unsigned successfully
 */
export const zEstimateControllerUnsignResponse = zReadEstimateDto;

export const zEstimateControllerRefuseData = z.object({
    body: z.never().optional(),
    path: z.object({
        estimateId: z.string().describe('ID of the estimate or purchase order to refuse')
    }),
    query: z.never().optional()
});

/**
 * Estimate or purchase order refused successfully
 */
export const zEstimateControllerRefuseResponse = zReadEstimateDto;

export const zEstimateControllerUnrefuseData = z.object({
    body: z.never().optional(),
    path: z.object({
        estimateId: z.string().describe('ID of the estimate or purchase order to unrefuse')
    }),
    query: z.never().optional()
});

/**
 * Estimate or purchase order unrefused successfully
 */
export const zEstimateControllerUnrefuseResponse = zReadEstimateDto;

export const zEstimateControllerCreateAdvanceData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice advance created successfully
 */
export const zEstimateControllerCreateAdvanceResponse = zReadAdvanceDto;

export const zEstimateControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateEstimateGeneralInformationsDto,
    path: z.object({
        estimateId: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Estimate general informations updated successfully
 */
export const zEstimateControllerUpdateGeneralInformationsResponse = zReadEstimateDto;

export const zEstimateControllerUpdateLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        estimateId: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Estimate locale updated successfully
 */
export const zEstimateControllerUpdateLocaleResponse = zReadEstimateDto;

export const zEstimateControllerUpdateCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        estimateId: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Asset currency updated successfully
 */
export const zEstimateControllerUpdateCurrencyResponse = zReadEstimateDto;

export const zEstimateControllerUpdateAdvanceLinesData = z.object({
    body: zUpdateEstimateAdvanceLinesDto,
    path: z.object({
        estimateId: z.string().describe('ID of the estimate to update')
    }),
    query: z.never().optional()
});

/**
 * Estimate advance lines updated successfully
 */
export const zEstimateControllerUpdateAdvanceLinesResponse = zReadEstimateDto;

export const zInvoiceControllerGetInvoiceData = z.object({
    body: z.never().optional(),
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to retrieve')
    }),
    query: z.never().optional()
});

/**
 * Invoice retrieved successfully
 */
export const zInvoiceControllerGetInvoiceResponse = zReadInvoiceDto;

export const zInvoiceControllerCreateInvoiceByContactOrOrganizationIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        customerId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Invoice created successfully
 */
export const zInvoiceControllerCreateInvoiceByContactOrOrganizationIdResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceLinesData = z.object({
    body: zUpdateBillingLinesDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice lines updated successfully
 */
export const zInvoiceControllerUpdateInvoiceLinesResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceDeliveryAddressData = z.object({
    body: zUpdateInvoiceDeliveryAddressDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice delivery address updated successfully
 */
export const zInvoiceControllerUpdateInvoiceDeliveryAddressResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateTimelineData = z.object({
    body: zUpdateInvoiceTimelineDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice timeline updated successfully
 */
export const zInvoiceControllerUpdateTimelineResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoicePaymentRequestData = z.object({
    body: zUpdateInvoicePaymentRequestDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Payment request updated successfully
 */
export const zInvoiceControllerUpdateInvoicePaymentRequestResponse = zReadInvoiceDto;

export const zInvoiceControllerFinalizeInvoiceData = z.object({
    body: z.never().optional(),
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to finalize')
    }),
    query: z.never().optional()
});

/**
 * Invoice finalized successfully
 */
export const zInvoiceControllerFinalizeInvoiceResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceGeneralInformationsData = z.object({
    body: zUpdateInvoiceGeneralInformationsDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice general informations updated successfully
 */
export const zInvoiceControllerUpdateInvoiceGeneralInformationsResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice locale updated successfully
 */
export const zInvoiceControllerUpdateInvoiceLocaleResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice currency updated successfully
 */
export const zInvoiceControllerUpdateInvoiceCurrencyResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateDisplaySettingsData = z.object({
    body: zUpdateBillingDisplaySettingsDto,
    path: z.object({
        invoiceId: z.string().describe('ID de la facture à mettre à jour')
    }),
    query: z.never().optional()
});

/**
 * Paramètres d'affichage de la facture mis à jour avec succès
 */
export const zInvoiceControllerUpdateDisplaySettingsResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceBankInformationData = z.object({
    body: zUpdateInvoiceBankInformationDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice bank information updated successfully
 */
export const zInvoiceControllerUpdateInvoiceBankInformationResponse = zReadInvoiceDto;

export const zInvoiceControllerDeleteInvoiceFrequencyData = z.object({
    body: z.never().optional(),
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice frequency deleted successfully
 */
export const zInvoiceControllerDeleteInvoiceFrequencyResponse = zReadInvoiceDto;

export const zInvoiceControllerCreateInvoiceFrequencyData = z.object({
    body: zCreateInvoiceFrequencyDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice frequency created successfully
 */
export const zInvoiceControllerCreateInvoiceFrequencyResponse = zReadInvoiceDto;

export const zInvoiceControllerUpdateInvoiceFrequencyData = z.object({
    body: zUpdateInvoiceFrequencyDto,
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to update'),
        frequencyId: z.unknown().describe('ID of the frequency to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice bank information updated successfully
 */
export const zInvoiceControllerUpdateInvoiceFrequencyResponse = zReadInvoiceDto;

export const zInvoiceControllerCreateAssetData = z.object({
    body: z.never().optional(),
    path: z.object({
        invoiceId: z.string().describe('ID of the invoice to create asset from')
    }),
    query: z.never().optional()
});

/**
 * Asset created successfully
 */
export const zInvoiceControllerCreateAssetResponse = zReadAssetDto;

export const zBillingControllerArchiveBillingDocumentData = z.object({
    body: z.never().optional(),
    path: z.object({
        documentId: z.string().describe('ID of the document to archive')
    }),
    query: z.never().optional()
});

/**
 * Document archived successfully
 */
export const zBillingControllerArchiveBillingDocumentResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerUnarchiveBillingDocumentData = z.object({
    body: z.never().optional(),
    path: z.object({
        documentId: z.string().describe('ID of the document to unarchive')
    }),
    query: z.never().optional()
});

/**
 * Document unarchived successfully
 */
export const zBillingControllerUnarchiveBillingDocumentResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerUpdateTitleData = z.object({
    body: zUpdateTitleDto,
    path: z.object({
        documentId: z.string().describe('ID of the document to update title')
    }),
    query: z.never().optional()
});

/**
 * Title updated successfully
 */
export const zBillingControllerUpdateTitleResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerGetBillingByIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        documentId: z.string().describe('ID of the billing document')
    }),
    query: z.never().optional()
});

/**
 * Billing document retrieved successfully
 */
export const zBillingControllerGetBillingByIdResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerUpdateBankInformationData = z.object({
    body: zUpdateBillingBankInformationDto,
    path: z.object({
        billingId: z.string().describe('ID of the billing to update')
    }),
    query: z.never().optional()
});

/**
 * Billing bank information updated successfully
 */
export const zBillingControllerUpdateBankInformationResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerUpdateBillingDeliveryAddressData = z.object({
    body: zUpdateBillingDeliveryAddressDto,
    path: z.object({
        billingId: z.string().describe('ID of the billing to update')
    }),
    query: z.never().optional()
});

/**
 * Billing delivery address updated successfully
 */
export const zBillingControllerUpdateBillingDeliveryAddressResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerFinalizeData = z.object({
    body: z.never().optional(),
    path: z.object({
        billingId: z.string().describe('ID of the billing to finalize')
    }),
    query: z.never().optional()
});

/**
 * Billing finalized successfully
 */
export const zBillingControllerFinalizeResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zBillingControllerUpdateLinesData = z.object({
    body: zUpdateBillingLinesDto,
    path: z.object({
        billingId: z.string().describe('ID of the billing to update')
    }),
    query: z.never().optional()
});

/**
 * Billing lines updated successfully
 */
export const zBillingControllerUpdateLinesResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAssetDto
]);

export const zBillingControllerMigrateSapProductsData = z.object({
    body: zMigrateSapProductsDto,
    path: z.object({
        billingId: z.string().describe('ID of the invoice to update')
    }),
    query: z.never().optional()
});

/**
 * Invoice lines updated successfully
 */
export const zBillingControllerMigrateSapProductsResponse = zReadInvoiceDto;

export const zBillingControllerToggleIncludeDiscountDisbursementData = z.object({
    body: z.object({
        includeDiscountDisbursement: z.boolean().optional()
    }),
    path: z.object({
        billingId: z.string().describe('ID of the billing to update')
    }),
    query: z.never().optional()
});

/**
 * Billing updated successfully
 */
export const zBillingControllerToggleIncludeDiscountDisbursementResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAssetDto
]);

export const zBillingControllerUpdateDisplaySettingsData = z.object({
    body: zUpdateBillingDisplaySettingsDto,
    path: z.object({
        billingId: z.string().describe('ID of the billing document to update')
    }),
    query: z.never().optional()
});

/**
 * Billing display settings updated successfully
 */
export const zBillingControllerUpdateDisplaySettingsResponse = z.union([
    zReadInvoiceDto,
    zReadEstimateDto,
    zReadAdvanceDto,
    zReadAssetDto
]);

export const zAdvanceControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateAdvanceGeneralInformationsDto,
    path: z.object({
        advanceId: z.string().describe('ID of the advance to update')
    }),
    query: z.never().optional()
});

/**
 * Advance general informations updated successfully
 */
export const zAdvanceControllerUpdateGeneralInformationsResponse = zReadAdvanceDto;

export const zAdvanceControllerCreateAssetData = z.object({
    body: z.never().optional(),
    path: z.object({
        advanceId: z.string().describe('ID of the invoice to create asset from')
    }),
    query: z.never().optional()
});

/**
 * Asset created successfully
 */
export const zAdvanceControllerCreateAssetResponse = zReadAssetDto;

export const zAssetControllerGetAssetData = z.object({
    body: z.never().optional(),
    path: z.object({
        assetId: z.string().describe('ID of the asset to retrieve')
    }),
    query: z.never().optional()
});

/**
 * Asset retrieved successfully
 */
export const zAssetControllerGetAssetResponse = zReadAssetDto;

export const zAssetControllerUpdateGeneralInformationsData = z.object({
    body: zUpdateAssetGeneralInformationsDto,
    path: z.object({
        assetId: z.string().describe('ID of the asset to update')
    }),
    query: z.never().optional()
});

/**
 * Asset general informations updated successfully
 */
export const zAssetControllerUpdateGeneralInformationsResponse = zReadAssetDto;

export const zAssetControllerUpdateLocaleData = z.object({
    body: zUpdateBillingLocaleDto,
    path: z.object({
        assetId: z.string().describe('ID of the asset to update')
    }),
    query: z.never().optional()
});

/**
 * Asset locale updated successfully
 */
export const zAssetControllerUpdateLocaleResponse = zReadAssetDto;

export const zAssetControllerUpdateCurrencyData = z.object({
    body: zUpdateBillingCurrencyDto,
    path: z.object({
        assetId: z.string().describe('ID of the asset to update')
    }),
    query: z.never().optional()
});

/**
 * Asset currency updated successfully
 */
export const zAssetControllerUpdateCurrencyResponse = zReadAssetDto;
